Table workspaces {
  id integer [pk]
  code varchar
  host varchar [not null, unique]
  name varchar
  phone_number varchar
  name_slug varchar
  parent_id  integer
  hierarchy_level integer
  is_active boolean [default: true]
}
Table users {
  id integer [pk]
  workspace_id integer
  phone_number varchar
  is_active boolean [default: true]
}
Table user_workspaces {
  id integer [pk]
  workspace_id integer
  user_id integer
  username varchar
  nickname varchar
  fullname varchar
  email varchar
  birthday varchar
  sex varchar
  lang varchar
  is_owner boolean
  is_active boolean [default: true]
  phone_number varchar
  avatar varchar
  address varchar
  status varchar
  zalo varchar
  skype varchar
  class_name_leaning varchar
  city_id integer
  country_id integer
  district_id integer
  ward_id integer
  birthplace varchar
  attach_image_url varchar
  referral_source varchar
  presenter_id integer
  school_name varchar
  note varchar
  facebook varchar
  user_type varchar
}
Table user_workspace_tokens {
  id integer [pk]
  user_workspace_id integer
  workspace_id integer
  access_token varchar
  refresh_token varchar
  status varchar
  is_active boolean [default: true]
}
Table user_workspace_devices {
  id integer [pk] 
  device_name varchar
  device_id integer
  fcm_push_token varchar
  device_platform varchar
  is_emulator boolean
  user_workspace_id integer
  workspace_id integer
  is_active boolean [default: true]
}
Table user_workspace_notifications{
  id integer [pk]
  title varchar
  platform varchar
  status varchar
  firebase_push_type varchar
  date timestamp
  push_type varchar
  notification_message_id integer
  receiver_user_workspace_id integer
  workspace_id integer
}
Table notification_messages {
  id integer [pk]
  title varchar
  body varchar
  description varchar
  metadata text
  firebase_push_type varchar
  date timestamp
  workspace_id integer
}
Table courses {
  id integer [pk]
  name varchar
  number_of_lesson integer
  payment_method varchar
  code varchar
  hours_of_lesson integer
  price integer
  subject varchar
  unit varchar
  workspace_id integer
}
Table lectures {
  id integer [pk]
  lesson_id integer
  name varchar
  content varchar
  exercise varchar
  equipment varchar
  is_use_name boolean
  lecture_file_id integer
  course_id integer
  workspace_id integer
}
Table files {
  id integer [pk]
  url varchar
  lecture_id integer
  post_id integer
  workspace_id integer
}
Table lessons {
  id integer [pk]
  name varchar
  content text [note: 'Nội dung bài học']
  exercise text [note: 'Bài tập về nhà']
  course_id integer
  workspace_id integer
}
Table skills {
  id integer [pk]
  name varchar
  rate_by varchar
  maximum_score integer
  status  varchar
  course_id integer
  workspace_id integer
}
Table characters_of_skill{
  id integer [pk]
  skill_id integer
  name varchar
  value integer
  workspace_id integer
}
Table assignments {
  id integer [pk]
  test_schedule_type  varchar
  test_schedule_value integer
  status varchar
  course_id integer
  workspace_id integer
}
Table assignment_skills {
  id integer [pk]
  assignment_id integer
  skill_id integer
  workspace_id integer
}
Table documents {
  id integer [pk]
  name varchar
  url varchar
  course_id integer
  workspace_id integer
}
Table classes {
  id integer [pk]
  name varchar
  course_id integer
  from_time timestamp
  to_time timestamp
  attended_number integer  [note: 'Đã học']
  session_number integer [note: 'Số buổi']
  code varchar
  status varchar
  workspace_id integer
}
Table user_workspace_courses {
  id integer [pk]
  course_id integer
  user_workspace_id integer
  workspace_id integer
}
Table posts {
  id integer [pk]
  content varchar
  class_id integer
  allow_comment boolean
  workspace_id integer
}
Table classrooms {
  id integer [pk]
  name  varchar
  code varchar
  seat_number integer
  status varchar
  workspace_id integer
}
Table permissions {
  id integer [pk]
  key varchar
  workspace_id integer
  is_active boolean [default: true]
  is_all_permissions boolean
  group_permission_id integer
}
Table cities{
  id integer [pk]
  name varchar
  code varchar
  country_id integer
  description varchar
  is_active boolean [default: true]
}
Table config{
  id integer [pk]
  name varchar
  value varchar
  platform varchar
  description varchar
}
Table countries{
  id integer [pk]
  name varchar
  code varchar
  description varchar
  is_active boolean [default: true]
}
Table wards{
  id integer [pk]
  name varchar
  code varchar
  country_id integer
  district_id integer
  city_id integer
  description varchar
  is_active boolean [default: true]
}
Table districts {
  id integer [pk]
  name varchar
  code varchar
  country_id integer
  city_id integer
  description varchar
  is_active boolean [default: true]
}
Table group_permissions{
  id integer [pk]
  name varchar
  description varchar
  workspace_id integer
  scope_key varchar
  is_super_admin boolean
  is_active boolean [default: true]
}
Table scope_permissions {
  id integer [pk]
  organization_id integer
  group_permission_id integer
  workspace_id integer
  is_active boolean [default: true]
}
Table organizations {
  id integer [pk]
  name varchar
  code varchar
  workspace_id integer
  is_active boolean [default: true]
}
Table video_files {
  id integer [pk]
  url varchar
  post_id integer
  workspace_id integer
}
Table image_files {
  id integer [pk]
  url varchar
  post_id integer
  workspace_id integer
}
Table shift_weekdays{
  id integer [pk]
  shift_id integer
  weekday number
  workspace_id integer
}
Table shifts {
  id integer [pk]
  from_time timestamp
  to_time timestamp
  is_everyday boolean
  workspace_id integer
}
Table timetables {
  id integer [pk]
  lesson_id integer
  classroom_id integer
  date timestamp
  shift_id integer
  workspace_id integer
}
Table user_workspace_timetables{
  id integer [pk]
  user_workspace_id integer
  timetable_id integer
  title varchar 
  note varchar
  from_time timestamp
  to_time timestamp
  workspace_id integer
}
Table events {
  id integer [pk]
  name varchar
  image varchar
  description varchar
  maximum_register integer
  from_time timestamp
  to_time timestamp
  register_from_time timestamp
  register_to_time timestamp
  content text
  is_important boolean
  schedule_send timestamp
  scope_send varchar
  workspace_id integer
}
Table appliance_absents {
  id integer [pk]
  user_workspace_id integer
  note varchar
  workspace_id integer
  class_id integer
}

Table course_unit_workspaces {
  id integer [pk]
  course_id integer
  unit_workspace_id integer
  workspace_id integer
}
Table daily_evaluations {
  id integer [pk]
  name varchar
  workspace_id integer
}
Table user_workspace_classes {
  id integer [pk]
  user_workspace_id integer
  course_id integer
  class_id integer
  workspace_id integer
  from_date date
  session_number integer
  note varchar
  class_schedule varchar
}
Table user_workspace_shift_scopes {
  id integer [pk]
  user_workspace_id integer
  class_shifts_classroom_id integer
  from_time date
  to_time date
  note varchar
  is_active boolean [default: true]
}
Table class_shifts_classrooms {
  id integer [pk]
  shift_id integer
  classroom_id integer
  class_id integer
  workspace_id integer
  valid_date date
  expires_date date
}
Table class_lessons {
  id integer [pk]
  name varchar
  content text [note: 'Nội dung bài học']
  exercise text [note: 'Bài tập về nhà']
  session_number_order integer
  class_id integer
  workspace_id integer
}
Table class_lectures {
  id integer [pk]
  class_lesson_id integer
  name varchar
  content varchar
  exercise varchar
  equipment varchar
  is_use_name boolean
  lecture_file_id integer
  session_number_order integer
  class_id integer
  workspace_id integer
}
Table class_timetable_details {
  id integer [pk]
  timetable_id integer
  user_workspace_id integer

  attendance_status varchar
  attendance_note varchar
  attendance_by_user_workspace_id integer
  homework_assignment varchar
  homework_score integer
  homework_assessment varchar
  homework_by_user_workspace_id varchar

  workspace_id integer
}

Table evaluation_criterias {
  id integer [pk]
  name varchar
  type varchar [note: 'nhập điểm | nhập văn bản | chọn 1 lựa chọn | chọn nhiều lựa chọn']
  status varchar
  maximum_score integer [note: ' với type nhập điểm: Điểm tối đa']
  daily_evaluation_id integer
  workspace_id integer
}
Table evaluation_option_values {
  id integer [pk]
  value varchar
  evaluation_criteria_id integer
  workspace_id integer
}
Table class_timetable_detail_evaluations {
  id integer [pk]
  class_timetable_detail_id integer
  evaluation_criteria_id integer
  score_value integer
  text_value varchar
  
  workspace_id integer
}
Table class_timetable_detail_evaluation_options {
  id integer [pk]
  class_timetable_detail_evaluation_id integer
  evaluation_option_value_id integer

  workspace_id integer
}
Table user_workspace_permissions {
  id integer [pk]
  user_workspace_id integer
  permission_id integer
  valid_date date
  expires_date date
  workspace_id integer
}
Table appliance_absent_timetables {
 id integer [pk] 
 timetable_id integer
 appliance_absent_id integer
 workspace_id integer
}
Table post_medias {
 id integer [pk] 
 post_id integer
 link varchar
 type varchar
 workspace_id integer
}
Table post_user_workspaces {
 id integer [pk] 
 post_id integer
 user_workspace_id integer
 workspace_id integer
}
Table user_workspace_supports {
 id integer [pk] 
 content varchar
 type varchar
 status varchar
 response_status varchar
 user_workspace_id integer
 workspace_id integer
}
Table user_workspace_support_images {
 id integer [pk] 
 user_workspace_support_id integer
 url varchar
 workspace_id integer
}
Table class_timetable_detail_assignments {
  id integer [pk]
  class_timetable_detail_id integer
  type varchar
  link varchar
  note varchar
  workspace_id integer
}
Table invoices {
  id integer [pk]
  code varchar
  user_workspace_id integer
  date timestamp
  due_date_payment timestamp
  total_payment integer
  paid_money integer
  discount integer
  current_paid integer
  payment_method varchar
}
Table contracts {
  id integer [pk]
  user_workspace_id integer
  code varchar
  paid_money integer
}
Table contract_courses {
  id integer [pk]
  course_id integer
  price integer
  discount integer
}