/* eslint-disable no-unused-vars */
import { CACHE_PREFIX } from './constants';

type ICacheRelations = {
  [k in CACHE_PREFIX]?: CACHE_PREFIX[];
};

/*
 * CACHE RELATIONS
 * [k in CACHE_PREFIX] means if have once add/update/destroy then caches in CACHE_PREFIX array will delete
 * CACHE_PREFIX[] means this cache has foreign key in the models
 * example 1: user_workspaces model has foreign key is staff_type_id. When has any add/update/destroy in staff_types then caches about user_workspaces must delete
 * example 2 job_titles models has foreign key is job_title_group_id. This is parent-children relationship
 */
export const cacheRelations: ICacheRelations = {
  [CACHE_PREFIX.CACHE_STAFF_TYPE]: [CACHE_PREFIX.CACHE_USER_WORKSPACE],
  [CACHE_PREFIX.CACHE_JOB_TITLE_GROUP]: [CACHE_PREFIX.CACHE_JOB_TITLE],
  [CACHE_PREFIX.CACHE_JOB_TITLE]: [CACHE_PREFIX.CACHE_USER_WORKSPACE, CACHE_PREFIX.CACHE_SALARY_INFORMATION],
  [CACHE_PREFIX.CACHE_FAMILY_RELATION]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_FAMILY_RELATION],
  [CACHE_PREFIX.CACHE_MATERIAL]: [CACHE_PREFIX.CACHE_MATERIAL_COMPENSATION],
  [CACHE_PREFIX.CACHE_MATERIAL_COMPENSATION]: [],
  [CACHE_PREFIX.CACHE_HEALTH_FACILITY]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_HEALTH, CACHE_PREFIX.CACHE_USER_WORKSPACE],
  [CACHE_PREFIX.CACHE_HEALTH_FACILITY_TYPE]: [CACHE_PREFIX.CACHE_HEALTH_FACILITY],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_HEALTH]: [],
  [CACHE_PREFIX.CACHE_ALLOWANCE]: [CACHE_PREFIX.CACHE_ALLOWANCE_TYPE],
  [CACHE_PREFIX.CACHE_ALLOWANCE_TYPE]: [CACHE_PREFIX.CACHE_ALLOWANCE],
  [CACHE_PREFIX.CACHE_BANK_BRANCH]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_BANK],
  [CACHE_PREFIX.CACHE_BANK]: [CACHE_PREFIX.CACHE_BANK_BRANCH, CACHE_PREFIX.CACHE_USER_WORKSPACE_BANK],
  [CACHE_PREFIX.CACHE_CITY]: [
    CACHE_PREFIX.CACHE_DISTRICT,
    CACHE_PREFIX.CACHE_WARD,
    CACHE_PREFIX.CACHE_COEFFICIENT_REGION,
    CACHE_PREFIX.CACHE_HEALTH_FACILITY,
  ],
  [CACHE_PREFIX.CACHE_COEFFICIENT_REGION]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_COEFFICIENT_REGION],
  [CACHE_PREFIX.CACHE_COEFFICIENT]: [CACHE_PREFIX.CACHE_COEFFICIENT_REGION],
  [CACHE_PREFIX.CACHE_COUNTRY]: [
    CACHE_PREFIX.CACHE_CITY,
    CACHE_PREFIX.CACHE_DISTRICT,
    CACHE_PREFIX.CACHE_WARD,
    CACHE_PREFIX.CACHE_COEFFICIENT_REGION,
  ],
  [CACHE_PREFIX.CACHE_DISCIPLINE_BEHAVIOR]: [CACHE_PREFIX.CACHE_DISCIPLINE_DECISION],
  [CACHE_PREFIX.CACHE_DISCIPLINE]: [CACHE_PREFIX.CACHE_DISCIPLINE_BEHAVIOR, CACHE_PREFIX.CACHE_DISCIPLINE_DECISION],
  [CACHE_PREFIX.CACHE_DISTRICT]: [CACHE_PREFIX.CACHE_WARD, CACHE_PREFIX.CACHE_COEFFICIENT_REGION, CACHE_PREFIX.CACHE_HEALTH_FACILITY],
  [CACHE_PREFIX.CACHE_INSURANCE]: [],
  [CACHE_PREFIX.CACHE_JOB_POSITION]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_JOB_POSITION, CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_JOB_POSITION]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN],
  [CACHE_PREFIX.CACHE_LABOR_CONTRACT]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_CONTRACT, CACHE_PREFIX.CACHE_USER_LABOR_ACTIVE],
  [CACHE_PREFIX.CACHE_MAJOR]: [CACHE_PREFIX.CACHE_OCCUPATION],
  [CACHE_PREFIX.CACHE_OCCUPATION]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_TRAINING],
  [CACHE_PREFIX.CACHE_ORGANIZATION]: [
    CACHE_PREFIX.CACHE_JOB_POSITION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_ORGANIZATION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_ORGANIZATION_BY_ROLE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_ORGANIZATION_BY_SPECIFY,
    CACHE_PREFIX.CACHE_USER_WORKSPACE,
    CACHE_PREFIX.CACHE_WORKSPACE_INVITE_CONFIG,
    CACHE_PREFIX.CACHE_USER_INVITE_REQUEST,
    CACHE_PREFIX.CACHE_ORGANIZATION_REWARD,
    CACHE_PREFIX.CACHE_ORGANIZATION_DISCIPLINE,
    CACHE_PREFIX.CACHE_ORGANIZATION_HIERARCHY,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_PERMISSION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN,
  ],
  [CACHE_PREFIX.CACHE_REWARD_TITLE]: [CACHE_PREFIX.CACHE_REWARD_DECISION],
  [CACHE_PREFIX.CACHE_REWARD_TITLE_TYPE]: [CACHE_PREFIX.CACHE_REWARD_TITLE, CACHE_PREFIX.CACHE_REWARD_DECISION],
  [CACHE_PREFIX.CACHE_UNIVERSITY]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_TRAINING],
  [CACHE_PREFIX.CACHE_USER_INVITE_CONFIG]: [CACHE_PREFIX.CACHE_USER_INVITE_REQUEST, CACHE_PREFIX.CACHE_WORKSPACE_INVITE_CONFIG],
  [CACHE_PREFIX.CACHE_USER_INVITE_REQUEST]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_BANK]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_CONTRACT]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_ORGANIZATION]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_ORGANIZATION_MEMOIZATION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_USER_WORKSPACE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_PERMISSION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN,
  ],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE]: [
    CACHE_PREFIX.CACHE_MATERIAL_COMPENSATION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_BANK,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_HEALTH,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_CONTRACT,
    CACHE_PREFIX.CACHE_COEFFICIENT_REGION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_JOB_POSITION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_TRAINING,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_ORGANIZATION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_ORGANIZATION_BY_ROLE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_ORGANIZATION_BY_SPECIFY,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_FAMILY_RELATION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_REWARD,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_DISCIPLINE,
    CACHE_PREFIX.CACHE_MEETING_GROUP,
    CACHE_PREFIX.CACHE_PAYROLL_POLICY,
    CACHE_PREFIX.CACHE_SALARY_INFORMATION,
    CACHE_PREFIX.CACHE_ADVANCE_APPLIANCE,
    CACHE_PREFIX.CACHE_SHIFT_APPLIANCE,
    CACHE_PREFIX.CACHE_CHANGE_SHIFT_APPLIANCE,
    CACHE_PREFIX.CACHE_ROTATE_SHIFT_APPLIANCE,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_SHIFT_SCHEDULE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_OVERTIME_APPLIANCE,
    CACHE_PREFIX.CACHE_WORKPLACE_POST,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_CHECKIN,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_CHECKIN_LOGS,
    CACHE_PREFIX.CACHE_MEETING_GROUP_MEMBER,
    CACHE_PREFIX.CACHE_MEETING,
    CACHE_PREFIX.CACHE_OFFICE_MEETING_ROOM,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_PERMISSION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN,
  ],
  [CACHE_PREFIX.CACHE_WARD]: [CACHE_PREFIX.CACHE_COEFFICIENT_REGION, CACHE_PREFIX.CACHE_HEALTH_FACILITY],
  [CACHE_PREFIX.CACHE_WORKSPACE_CATEGORY]: [],
  [CACHE_PREFIX.CACHE_WORKSPACE_INVITE_CONFIG]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_TRAINING]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_FAMILY_RELATION]: [],

  /**
   * * Reward Decision
   */
  [CACHE_PREFIX.CACHE_REWARD_DECISION]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_REWARD, CACHE_PREFIX.CACHE_ORGANIZATION_REWARD],

  /**
   * * Discipline Decision
   */
  [CACHE_PREFIX.CACHE_DISCIPLINE_DECISION]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_DISCIPLINE, CACHE_PREFIX.CACHE_ORGANIZATION_DISCIPLINE],

  /**
   * * Leave type
   */
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_SCOPE]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_LOG]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_STATISTIC]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_SCOPE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],
  [CACHE_PREFIX.CACHE_LEAVE_TYPE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_SCOPE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_LOG,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  [CACHE_PREFIX.CACHE_WORKSPACE]: [...Object.values(CACHE_PREFIX)],
  [CACHE_PREFIX.CACHE_APPLIANCE_CONFIG]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_APPLIANCE_STEP,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
  ],
  [CACHE_PREFIX.CACHE_APPLIANCE_STEP]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE],
  [CACHE_PREFIX.CACHE_APPLIANCE_STEP_APPROVER]: [CACHE_PREFIX.CACHE_APPLIANCE_STEP, CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE],
  [CACHE_PREFIX.CACHE_SHIFT]: [
    CACHE_PREFIX.CACHE_SHIFT_HOUR,
    CACHE_PREFIX.CACHE_SHIFT_BREAK,
    CACHE_PREFIX.CACHE_SHIFT_TIME_COMPENSATION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_CLAIM_WORKING_DAY_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_CHECKIN,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
  ],
  [CACHE_PREFIX.CACHE_SHIFT_HOUR]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_CHECKIN,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
  ],
  [CACHE_PREFIX.CACHE_SHIFT_BREAK]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
  ],
  [CACHE_PREFIX.CACHE_SHIFT_TIME_COMPENSATION]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
  ],
  [CACHE_PREFIX.CACHE_SHIFT_GROUP]: [
    CACHE_PREFIX.CACHE_CHANGE_SHIFT_APPLIANCE,
    CACHE_PREFIX.CACHE_ROTATE_SHIFT_APPLIANCE,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_CLAIM_WORKING_DAY_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_CHECKIN,
    CACHE_PREFIX.CACHE_SHIFT_GROUP_OFFICE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
    CACHE_PREFIX.CACHE_SHIFT_GROUP_SPECIAL_DATE,
    CACHE_PREFIX.CACHE_SHIFT_APPLIANCE,
  ],
  [CACHE_PREFIX.CACHE_SHIFT_GROUP_SCHEDULE]: [
    CACHE_PREFIX.CACHE_SHIFT_GROUP,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_CHANGE_SHIFT_APPLIANCE,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
    CACHE_PREFIX.CACHE_SHIFT_APPLIANCE,
  ],

  /**
   * Shift group
   */
  [CACHE_PREFIX.CACHE_SHIFT_GROUP_SPECIAL_DATE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE,
  ],

  /**
   * Overtimes
   */
  [CACHE_PREFIX.CACHE_OVERTIME]: [],

  /**
   * Rotate shift appliance
   */
  [CACHE_PREFIX.CACHE_ROTATE_SHIFT_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],
  [CACHE_PREFIX.CACHE_SHIFT_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  [CACHE_PREFIX.CACHE_CHANGE_SHIFT_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],
  [CACHE_PREFIX.CACHE_SHIFT_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  [CACHE_PREFIX.CACHE_CHANGE_SHIFT_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],
  /**
   * Rotate shift appliance
   */
  [CACHE_PREFIX.CACHE_SHIFT_SCHEDULE_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  /**
   * Remote working appliance
   */
  [CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  /**
   * User workspace leave type appliance dates
   */
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE_DATE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  /**
   * Remote working appliance dates
   */
  [CACHE_PREFIX.CACHE_REMOTE_WORKING_APPLIANCE_DATE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  [CACHE_PREFIX.CACHE_SALARY_GRADES]: [CACHE_PREFIX.CACHE_SALARY_RANK],
  /**
   * Salary Parameters
   */
  [CACHE_PREFIX.CACHE_SALARY_PARAMETER]: [CACHE_PREFIX.CACHE_MINIMUM_NORM, CACHE_PREFIX.CACHE_MINIMUM_AMOUNT],

  [CACHE_PREFIX.CACHE_SALARY_PERIOD]: [],
  [CACHE_PREFIX.CACHE_SALARY_RANK]: [],
  [CACHE_PREFIX.CACHE_MINIMUM_AMOUNT]: [CACHE_PREFIX.CACHE_MINIMUM_NORM],
  [CACHE_PREFIX.CACHE_MINIMUM_NORM]: [CACHE_PREFIX.CACHE_MINIMUM_AMOUNT],

  /**
   * Reports
   */
  [CACHE_PREFIX.CACHE_REPORT]: [CACHE_PREFIX.CACHE_REPORT_HISTORY, CACHE_PREFIX.CACHE_INFORMATION_EXPORT_ATTRIBUTE],
  [CACHE_PREFIX.CACHE_REPORT_HISTORY]: [],
  [CACHE_PREFIX.CACHE_CATEGORY_EXPORT_ATTRIBUTE]: [CACHE_PREFIX.CACHE_INFORMATION_EXPORT_ATTRIBUTE],
  [CACHE_PREFIX.CACHE_INFORMATION_EXPORT_ATTRIBUTE]: [],

  /**
   * Meetings
   */
  [CACHE_PREFIX.CACHE_UTILITIES]: [CACHE_PREFIX.CACHE_OFFICE_MEETING_ROOM],
  [CACHE_PREFIX.CACHE_OFFICE_MEETING_ROOM]: [CACHE_PREFIX.CACHE_MEETING, CACHE_PREFIX.CACHE_MEETING_GROUP],
  [CACHE_PREFIX.CACHE_MEETING_GROUP]: [CACHE_PREFIX.CACHE_MEETING],
  [CACHE_PREFIX.CACHE_MEETING_GROUP_MEMBER]: [CACHE_PREFIX.CACHE_MEETING_GROUP],
  [CACHE_PREFIX.CACHE_MEETING]: [CACHE_PREFIX.CACHE_MEETING_GROUP],

  [CACHE_PREFIX.CACHE_REIMBURSEMENT]: [],
  [CACHE_PREFIX.CACHE_PAYROLL_POLICY]: [CACHE_PREFIX.CACHE_PAYROLL_ELEMENT],
  [CACHE_PREFIX.CACHE_SALARY_INFORMATION]: [],
  [CACHE_PREFIX.CACHE_PAYROLL_ELEMENT]: [],
  [CACHE_PREFIX.CACHE_DASHBOARD_SETTING]: [],
  [CACHE_PREFIX.CACHE_PAYROLL_TABLE]: [CACHE_PREFIX.CACHE_PAYROLL_TABLE_HISTORY],
  [CACHE_PREFIX.CACHE_PAYSLIP]: [CACHE_PREFIX.CACHE_PAYROLL_TABLE_HISTORY, CACHE_PREFIX.CACHE_PAYROLL_TABLE],
  [CACHE_PREFIX.CACHE_PAYROLL_TABLE_HISTORY]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE]: [],
  [CACHE_PREFIX.CACHE_ADVANCE_APPLIANCE]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_SHIFTS]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
  ],
  [CACHE_PREFIX.CACHE_CLAIM_WORKING_DAY_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],
  [CACHE_PREFIX.CACHE_OVERTIME_APPLIANCE]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_APPLIANCE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  /**
   * Workplace
   */
  [CACHE_PREFIX.CACHE_WORKPLACE_POST]: [],
  [CACHE_PREFIX.CACHE_WORKPLACE_POST_COMMENT]: [CACHE_PREFIX.CACHE_WORKPLACE_POST],
  [CACHE_PREFIX.CACHE_WORKPLACE_CONFIG]: [],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_CHECKIN]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
  ],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_CHECKIN_LOGS]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC, CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY],
  [CACHE_PREFIX.CACHE_SHIFT_GROUP_OFFICE]: [CACHE_PREFIX.CACHE_SHIFT_GROUP_OFFICE_CHECKIN_TYPE, CACHE_PREFIX.CACHE_CHECKIN_TYPE],
  [CACHE_PREFIX.CACHE_SHIFT_GROUP_OFFICE_CHECKIN_TYPE]: [CACHE_PREFIX.CACHE_CHECKIN_TYPE],
  [CACHE_PREFIX.CACHE_OFFICE_LOCATION]: [CACHE_PREFIX.CACHE_CHECKIN_TYPE],
  [CACHE_PREFIX.CACHE_OFFICE_WIFI]: [CACHE_PREFIX.CACHE_CHECKIN_TYPE],
  [CACHE_PREFIX.CACHE_MACHINE]: [],
  [CACHE_PREFIX.CACHE_OFFICE]: [
    CACHE_PREFIX.CACHE_MACHINE,
    CACHE_PREFIX.CACHE_OFFICE_WIFI,
    CACHE_PREFIX.CACHE_OFFICE_LOCATION,
    CACHE_PREFIX.CACHE_SHIFT_GROUP_OFFICE_CHECKIN_TYPE,
    CACHE_PREFIX.CACHE_SHIFT_GROUP_OFFICE,
    CACHE_PREFIX.CACHE_OFFICE_MEETING_ROOM,
    CACHE_PREFIX.CACHE_CHECKIN_TYPE,
  ],
  [CACHE_PREFIX.CACHE_DAY_OFF_GROUP]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC, CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY],
  [CACHE_PREFIX.CACHE_DAY_OFF]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC, CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_WORKING_DAY_INTEGRATION]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_STATISTIC_DAILY,
  ],

  /**
   * Workspace permission
   */
  [CACHE_PREFIX.CACHE_GROUP_PERMISSION]: [
    CACHE_PREFIX.CACHE_USER_WORKSPACE,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_PERMISSION,
    CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN,
  ],
  [CACHE_PREFIX.CACHE_USER_WORKSPACE_PERMISSION]: [CACHE_PREFIX.CACHE_USER_WORKSPACE, CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN],
  [CACHE_PREFIX.CACHE_USER]: [CACHE_PREFIX.CACHE_USER_WORKSPACE, CACHE_PREFIX.CACHE_USER_INVITE_REQUEST, CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN],

  /**
   * User workspace device
   */

  [CACHE_PREFIX.CACHE_USER_WORKSPACE_DEVICE]: [CACHE_PREFIX.CACHE_USER_WORKSPACE_TOKEN],
};
