/* eslint-disable no-unused-vars */

export enum CACHE_PREFIX {
  /**
   * Workspace permission
   */
  CACHE_CHECKIN_CONFIG = 'CACHE_CHECKIN_CONFIG',
  CACHE_GROUP_PERMISSION = 'CACHE_GROUP_PERMISSION',
  CACHE_USER_WORKSPACE_PERMISSION = 'CACHE_USER_WORKSPACE_PERMISSION',
  CACHE_USER = 'CACHE_USER',
  CACHE_USER_WORKSPACE_TOKEN = 'CACHE_USER_WORKSPACE_TOKEN',

  CACHE_USER_WORKSPACE_DEVICE = 'CACHE_USER_WORKSPACE_DEVICE',
  CACHE_WORKSPACE = 'CACHE_WORKSPACE',
  CACHE_USER_WORKSPACE = 'CACHE_USER_WORKSPACE',

  /**
   * Timetable
   */
  CACHE_TIMETABLE = 'CACHE_TIMETABLE',
  /**
   * Post
   */
  CACHE_POST = 'CACHE_POST',
  /**
   * Dashboard
   */
  CACHE_DASHBOARD = 'CACHE_DASHBOARD',
}
