/* eslint-disable no-unused-vars */

export enum CACHE_PREFIX {
  REQUEST_JOIN_WORKSPACE = 'REQUEST_JOIN_WORKSPACE1',
  CALLBACK_VERIFY_ACCOUNT = 'CALLBACK_VERIFY_ACCOUNT1',
  CACHE_STAFF_TYPE = 'CACHE_STAFF_TYPE1',
  CACHE_JOB_TITLE_GROUP = 'CACHE_JOB_TITLE_GROUP1',
  CACHE_JOB_TITLE = 'CACHE_JOB_TITLE1',
  CACHE_FAMILY_RELATION = 'CACHE_FAMILY_RELATION1',
  CACHE_MATERIAL = 'CACHE_MATERIAL1',
  CACHE_MATERIAL_COMPENSATION = 'CACHE_MATERIAL_COMPENSATION1',
  CACHE_HEALTH_FACILITY = 'CACHE_HEALTH_FACILITY1',
  CACHE_HEALTH_FACILITY_TYPE = 'CACHE_HEALTH_FACILITY_TYPE1',
  CACHE_USER_WORKSPACE_HEALTH = 'CACHE_USER_WORKSPACE_HEALTH1',
  CACHE_ALLOWANCE = 'CACHE_ALLOWANCE1',
  CACHE_ALLOWANCE_TYPE = 'CACHE_ALLOWANCE_TYPE1',
  CACHE_BANK_BRANCH = 'CACHE_BANK_BRANCH1',
  CACHE_BANK = 'CACHE_BANK1',
  CACHE_REGION = 'CACHE_REGION1',
  CACHE_CITY = 'CACHE_CITY1',
  CACHE_COEFFICIENT_REGION = 'CACHE_COEFFICIENT_REGION1',
  CACHE_COEFFICIENT = 'CACHE_COEFFICIENT1',
  CACHE_COUNTRY = 'CACHE_COUNTRY1',
  CACHE_DISCIPLINE_BEHAVIOR = 'CACHE_DISCIPLINE_BEHAVIOR1',
  CACHE_DISCIPLINE = 'CACHE_DISCIPLINE1',
  CACHE_DISTRICT = 'CACHE_DISTRICT1',
  CACHE_INSURANCE = 'CACHE_INSURANCE1',
  CACHE_JOB_POSITION = 'CACHE_JOB_POSITION1',
  CACHE_LABOR_CONTRACT = 'CACHE_LABOR_CONTRACT1',
  CACHE_MAJOR = 'CACHE_MAJOR1',
  CACHE_OCCUPATION = 'CACHE_OCCUPATION1',
  CACHE_ORGANIZATION = 'CACHE_ORGANIZATION1',
  CACHE_ORGANIZATION_HIERARCHY = 'CACHE_ORGANIZATION_HIERARCHY1',
  CACHE_REWARD_TITLE = 'CACHE_REWARD_TITLE1',
  CACHE_REWARD_TITLE_TYPE = 'CACHE_REWARD_TITLE_TYPE1',
  CACHE_UNIVERSITY = 'CACHE_UNIVERSITY1',
  CACHE_USER_INVITE_CONFIG = 'CACHE_USER_INVITE_CONFIG1',
  CACHE_USER_INVITE_REQUEST = 'CACHE_USER_INVITE_REQUEST1',
  CACHE_USER_WORKSPACE_BANK = 'CACHE_USER_WORKSPACE_BANK1',
  CACHE_USER_WORKSPACE_CONTRACT = 'CACHE_USER_WORKSPACE_CONTRACT1',
  CACHE_USER_WORKSPACE_ORGANIZATION = 'CACHE_USER_WORKSPACE_ORGANIZATION1',
  CACHE_USER_WORKSPACE_ORGANIZATION_MEMOIZATION = 'CACHE_USER_WORKSPACE_ORGANIZATION_MEMOIZATION1',
  CACHE_USER_WORKSPACE_ORGANIZATION_BY_ROLE = 'CACHE_USER_WORKSPACE_ORGANIZATION_BY_ROLE1',
  CACHE_USER_WORKSPACE_ORGANIZATION_BY_SPECIFY = 'CACHE_USER_WORKSPACE_ORGANIZATION_BY_SPECIFY1',
  CACHE_USER_WORKSPACE_JOB_POSITION = 'CACHE_USER_WORKSPACE_JOB_POSITION1',
  CACHE_USER_WORKSPACE_COEFFICIENT_REGION = 'CACHE_USER_WORKSPACE_COEFFICIENT_REGION1',
  CACHE_USER_WORKSPACE = 'CACHE_USER_WORKSPACE',
  CACHE_WARD = 'CACHE_WARD1',
  CACHE_WORKSPACE_CATEGORY = 'CACHE_WORKSPACE_CATEGORY1',
  CACHE_WORKSPACE_INVITE_CONFIG = 'CACHE_WORKSPACE_INVITE_CONFIG1',
  CACHE_USER_WORKSPACE_TRAINING = 'CACHE_USER_WORKSPACE_TRAINING1',
  CACHE_USER_WORKSPACE_FAMILY_RELATION = 'CACHE_USER_WORKSPACE_FAMILY_RELATION1',
  CACHE_USER_WORKSPACE_ALLOWANCE = 'CACHE_USER_WORKSPACE_ALLOWANCE1',
  CACHE_USER_WORKSPACE_SOCIAL_INSURANCE = 'CACHE_USER_WORKSPACE_SOCIAL_INSURANCE1',
  CACHE_USER_WORKSPACE_HEALTH_INSURANCE = 'CACHE_USER_WORKSPACE_HEALTH_INSURANCE1',
  CACHE_USER_WORKSPACE_INSURANCE = 'CACHE_USER_WORKSPACE_INSURANCE1',
  CACHE_REWARD_DECISION = 'CACHE_REWARD_DECISION1',
  CACHE_USER_WORKSPACE_REWARD = 'CACHE_USER_WORKSPACE_REWARD1',
  CACHE_ORGANIZATION_REWARD = 'CACHE_ORGANIZATION_REWARD1',
  CACHE_DISCIPLINE_DECISION = 'CACHE_DISCIPLINE_DECISION1',
  CACHE_USER_WORKSPACE_DISCIPLINE = 'CACHE_USER_WORKSPACE_DISCIPLINE1',
  CACHE_ORGANIZATION_DISCIPLINE = 'CACHE_ORGANIZATION_DISCIPLINE1',
  CACHE_LEAVE_TYPE = 'CACHE_LEAVE_TYPE1',
  CACHE_USER_WORKSPACE_WORK_PROGRESS = 'CACHE_USER_WORKSPACE_WORK_PROGRESS1',
  CACHE_USER_LABOR_ACTIVE = 'CACHE_USER_LABOR_ACTIVE1',
  CACHE_USER_WORKSPACE_LEAVE_SCOPE = 'CACHE_USER_WORKSPACE_LEAVE_SCOPE1',
  CACHE_USER_WORKSPACE_LEAVE_LOG = 'CACHE_USER_WORKSPACE_LEAVE_LOG1',
  CACHE_LEAVE_TYPE_RULE = 'CACHE_LEAVE_TYPE_RULE1',
  CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE = 'CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE1',
  CACHE_USER_WORKSPACE_LEAVE_STATISTIC = 'CACHE_USER_WORKSPACE_LEAVE_STATISTIC1',
  CACHE_USER_CHECKIN_IMAGES = 'CACHE_USER_CHECKIN_IMAGES',

  CACHE_DAY_OFF_BY_GROUP = 'CACHE_DAY_OFF_BY_GROUP1',
  CACHE_DAY_OFF_GROUP = 'CACHE_DAY_OFF_GROUP1',
  CACHE_DAY_OFF = 'CACHE_DAY_OFF1',

  /**
   * * Approval Flow
   */
  CACHE_APPROVAL_GROUP = 'CACHE_APPROVAL_GROUP1',
  CACHE_APPROVAL_CATEGORY = 'CACHE_APPROVAL_CATEGORY1',
  CACHE_APPROVAL = 'CACHE_APPROVAL1',
  CACHE_APPROVAL_USER = 'CACHE_APPROVAL_USER1',
  CACHE_APPROVAL_NODE = 'CACHE_APPROVAL_NODE1',
  CACHE_APPROVAL_NODE_INFO = 'CACHE_APPROVAL_NODE_INFO1',
  CACHE_APPROVAL_NODE_TRANSFER_APPROVER = 'CACHE_APPROVAL_NODE_TRANSFER_APPROVER1',
  CACHE_APPROVAL_NODE_APPROVER_SETTING = 'CACHE_APPROVAL_NODE_APPROVER_SETTING1',
  CACHE_APPROVAL_NODE_SPECIFY_APPROVER = 'CACHE_APPROVAL_NODE_SPECIFY_APPROVER1',
  CACHE_APPROVAL_NODE_CONDITION_GROUP = 'CACHE_APPROVAL_NODE_CONDITION_GROUP1',
  CACHE_APPROVAL_NODE_CONDITION_REQUESTER = 'CACHE_APPROVAL_NODE_CONDITION_REQUESTER1',
  CACHE_APPROVAL_NODE_CONDITION_REQUESTER_USER_WORKSPACE = 'CACHE_APPROVAL_NODE_CONDITION_REQUESTER_USER_WORKSPACE1',
  CACHE_APPROVAL_NODE_CONDITION_REQUESTER_ORGANIZATION = 'CACHE_APPROVAL_NODE_CONDITION_REQUESTER_ORGANIZATION1',
  CACHE_APPROVAL_NODE_CONDITION_LEAVE_TYPE = 'CACHE_APPROVAL_NODE_CONDITION_LEAVE_TYPE1',
  CACHE_APPROVAL_NODE_CONDITION_LEAVE_DURATION = 'CACHE_APPROVAL_NODE_CONDITION_LEAVE_DURATION1',
  CACHE_APPROVAL_NODE_CONDITION_OVERTIME_DURATION = 'CACHE_APPROVAL_NODE_CONDITION_OVERTIME_DURATION1',
  CACHE_APPROVAL_LINE = 'CACHE_APPROVAL_LINE1',
  CACHE_WORKSPACE = 'CACHE_WORKSPACE',
  CACHE_APPROVAL_APPLIED_LEAVE_TYPE = 'CACHE_APPROVAL_APPLIED_LEAVE_TYPE1',
  CACHE_APPROVAL_NODE_REQUESTER_SELF_SELECTION_ROLE = 'CACHE_APPROVAL_NODE_REQUESTER_SELF_SELECTION_ROLE1',
  CACHE_APPROVAL_SWITCH = 'CACHE_APPROVAL_SWITCH1',
  CACHE_APPLIANCE_CONFIG = 'CACHE_APPLIANCE_CONFIG1',
  CACHE_APPLIANCE_STEP = 'CACHE_APPLIANCE_STEP1',
  CACHE_APPLIANCE_STEP_APPROVER = 'CACHE_APPLIANCE_STEP_APPROVER1',
  CACHE_SHIFT = 'CACHE_SHIFT1',
  CACHE_SHIFT_HOUR = 'CACHE_SHIFT_HOUR1',
  CACHE_SHIFT_BREAK = 'CACHE_SHIFT_BREAK1',
  CACHE_SHIFT_TIME_COMPENSATION = 'CACHE_SHIFT_TIME_COMPENSATION1',
  CACHE_SHIFT_GROUP = 'CACHE_SHIFT_GROUP1',
  CACHE_SHIFT_GROUP_SCHEDULE = 'CACHE_SHIFT_GROUP_SCHEDULE1',
  CACHE_APPROVAL_NODE_CONDITION_REMOTE_WORKING_DURATION = 'CACHE_APPROVAL_NODE_CONDITION_REMOTE_WORKING_DURATION1',
  CACHE_APPROVAL_NODE_CONDITION_ADVANCE_AMOUNT = 'CACHE_APPROVAL_NODE_CONDITION_ADVANCE_AMOUNT1',
  CACHE_USER_WORKSPACE_DEVICE = 'CACHE_USER_WORKSPACE_DEVICE1',

  /**
   * * Checkin type
   */
  CACHE_MACHINE = 'CACHE_MACHINE1',
  CACHE_CHECKIN_TYPE = 'CACHE_CHECKIN_TYPE1',

  /**
   * Shift group special date
   */
  CACHE_SHIFT_GROUP_SPECIAL_DATE = 'CACHE_SHIFT_GROUP_SPECIAL_DATE1',

  /**
   * Overtimes
   */
  CACHE_OVERTIME = 'CACHE_OVERTIME1',

  /**
   * Rotate shift appliance
   */
  CACHE_ROTATE_SHIFT_APPLIANCE = 'CACHE_ROTATE_SHIFT_APPLIANCE1',
  CACHE_SHIFT_APPLIANCE = 'CACHE_SHIFT_APPLIANCE1',

  /**
   * Change shift appliance
   */
  CACHE_CHANGE_SHIFT_APPLIANCE = 'CACHE_CHANGE_SHIFT_APPLIANCE1',

  /* Rotate shift appliance
   */
  CACHE_SHIFT_SCHEDULE_APPLIANCE = 'CACHE_SHIFT_SCHEDULE_APPLIANCE1',

  /**
   * Remote working
   */
  CACHE_REMOTE_WORKING_APPLIANCE = 'CACHE_REMOTE_WORKING_APPLIANCE1',

  /**
   * User workspace leave type appliance dates
   */
  CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE_DATE = 'CACHE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE_DATE1',

  /**
   * Remote working appliance dates
   */
  CACHE_REMOTE_WORKING_APPLIANCE_DATE = 'CACHE_REMOTE_WORKING_APPLIANCE_DATE1',
  CACHE_OFFICE = 'CACHE_OFFICE1',

  CACHE_SALARY_GRADES = 'CACHE_SALARY_GRADES1',
  CACHE_SALARY_PERIOD = 'CACHE_SALARY_PERIOD1',
  /**
   * Salary Parameters
   */
  CACHE_SALARY_PARAMETER = 'CACHE_SALARY_PARAMETER1',

  CACHE_SALARY_RANK = 'CACHE_SALARY_RANK1',
  /**
   * Minimum amount
   */
  CACHE_MINIMUM_AMOUNT = 'CACHE_MINIMUM_AMOUNT1',
  CACHE_MINIMUM_NORM = 'CACHE_MINIMUM_NORM1',
  CACHE_SALARY_METHOD_CONFIG = 'CACHE_SALARY_METHOD_CONFIG1',
  CACHE_SALARY_METHOD_CONFIG_SCOPE = 'CACHE_SALARY_METHOD_CONFIG_SCOPE1',
  CACHE_SALARY_METHOD_CONFIG_GRADE = 'CACHE_SALARY_METHOD_CONFIG_GRADE1',
  CACHE_SALARY_METHOD_CONFIG_RANK = 'CACHE_SALARY_METHOD_CONFIG_RANK1',
  CACHE_SALARY_PAY_METHOD = 'CACHE_SALARY_PAY_METHOD1',

  /**
   * Reports
   */
  CACHE_REPORT = 'CACHE_REPORT1',
  CACHE_REPORT_HISTORY = 'CACHE_REPORT_HISTORY1',
  CACHE_CATEGORY_EXPORT_ATTRIBUTE = 'CACHE_CATEGORY_EXPORT_ATTRIBUTE1',
  CACHE_INFORMATION_EXPORT_ATTRIBUTE = 'CACHE_INFORMATION_EXPORT_ATTRIBUTE1',

  CACHE_COMPANY = 'CACHE_COMPANY1',
  CACHE_UTILITIES = 'CACHE_UTILITIES1',
  CACHE_OFFICE_MEETING_ROOM = 'CACHE_OFFICE_MEETING_ROOM1',
  CACHE_MEETING_GROUP = 'CACHE_MEETING_GROUP1',
  CACHE_MEETING_GROUP_MEMBER = 'CACHE_MEETING_GROUP_MEMBER1',
  CACHE_MEETING = 'CACHE_MEETING1',

  CACHE_REIMBURSEMENT = 'CACHE_REIMBURSEMENT1',
  /**
   * Workplace
   */
  CACHE_WORKPLACE_POST = 'CACHE_WORKPLACE_POST1',
  CACHE_WORKPLACE_POST_COMMENT = 'CACHE_WORKPLACE_POST_COMMENT1',
  CACHE_WORKPLACE_CONFIG = 'CACHE_WORKPLACE_CONFIG1',

  CACHE_PAYROLL_POLICY = 'CACHE_PAYROLL_POLICY1',
  CACHE_SALARY_INFORMATION = 'CACHE_SALARY_INFORMATION1',
  CACHE_PAYROLL_ELEMENT = 'CACHE_PAYROLL_ELEMENT1',
  CACHE_PAYROLL_TABLE = 'CACHE_PAYROLL_TABLE1',
  CACHE_PAYSLIP = 'CACHE_PAYSLIP1',
  CACHE_DASHBOARD_SETTING = 'CACHE_DASHBOARD_SETTING1',
  CACHE_PAYROLL_TABLE_HISTORY = 'CACHE_PAYROLL_TABLE_HISTORY1',

  /**
   * * Cache Advance Payment Config
   */
  CACHE_ADVANCE_PAYMENT_CONFIG = 'CACHE_ADVANCE_PAYMENT_CONFIG1',
  CACHE_RANGE_ADVANCE_PAYMENT_CONFIG = 'CACHE_RANGE_ADVANCE_PAYMENT_CONFIG1',
  CACHE_RECOVERY_ADVANCE = 'CACHE_RECOVERY_ADVANCE1',
  CACHE_QRCODE_LOGIN_CMS = 'CACHE_QRCODE_LOGIN_CMS1',

  CACHE_USER_WORKSPACE_APPLIANCE = 'CACHE_USER_WORKSPACE_APPLIANCE1',
  CACHE_ADVANCE_APPLIANCE = 'CACHE_ADVANCE_APPLIANCE1',
  CACHE_CLAIM_WORKING_DAY_APPLIANCE = 'CACHE_CLAIM_WORKING_DAY_APPLIANCE1',
  CACHE_OVERTIME_APPLIANCE = 'CACHE_OVERTIME_APPLIANCE1',
  /**
   * User Workspace shift
   */
  CACHE_USER_WORKSPACE_SHIFTS = 'CACHE_USER_WORKSPACE_SHIFTS1',
  CACHE_USER_WORKSPACE_CHECKIN = 'CACHE_USER_WORKSPACE_CHECKIN1',
  CACHE_USER_WORKSPACE_CHECKIN_LOGS = 'CACHE_USER_WORKSPACE_CHECKIN_LOGS1',
  CACHE_SHIFT_GROUP_OFFICE = 'CACHE_SHIFT_GROUP_OFFICE1',
  CACHE_SHIFT_GROUP_OFFICE_CHECKIN_TYPE = 'CACHE_SHIFT_GROUP_OFFICE_CHECKIN_TYPE1',
  CACHE_OFFICE_LOCATION = 'CACHE_OFFICE_LOCATION1',
  CACHE_OFFICE_WIFI = 'CACHE_OFFICE_WIFI1',

  CACHE_USER_WORKSPACE_STATISTIC = 'CACHE_USER_WORKSPACE_STATISTIC1',
  CACHE_USER_WORKSPACE_STATISTIC_DAILY = 'CACHE_USER_WORKSPACE_STATISTIC_DAILY1',
  CACHE_USER_WORKSPACE_WORKING_DAY_INTEGRATION = 'CACHE_USER_WORKSPACE_WORKING_DAY_INTEGRATION1',
  CACHE_USER_WORKSPACE_SHIFT_WORKING_DAY = 'CACHE_USER_WORKSPACE_SHIFT_WORKING_DAY1',

  /**
   * Workspace permission
   */
  CACHE_CHECKIN_CONFIG = 'CACHE_CHECKIN_CONFIG1',
  CACHE_GROUP_PERMISSION = 'CACHE_GROUP_PERMISSION1',
  CACHE_USER_WORKSPACE_PERMISSION = 'CACHE_USER_WORKSPACE_PERMISSION1',
  CACHE_USER = 'CACHE_USER1',
  CACHE_USER_WORKSPACE_TOKEN = 'CACHE_USER_WORKSPACE_TOKEN1',

  CACHE_WORKSPACE_ADD_PROJECT_LOG = 'CACHE_WORKSPACE_ADD_PROJECT_LOG1',

  /**
   * Timetable
   */
  CACHE_TIMETABLE = 'CACHE_TIMETABLE',
}
