/* eslint-disable no-unused-vars */
enum ERROR {
  UNKNOWN = 'UNKNOWN',
  VALIDATE_FAILED = 'VALIDATE_FAILED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  DATA_IS_EXIST = 'DATA_IS_EXIST',
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  WORKSPACE_IS_EXIST = 'WORKSPACE_IS_EXIST',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_IS_EXIST = 'USER_IS_EXIST',
  OWNER_WORKSPACE_NOT_FOUND = 'OWNER_WORKSPACE_NOT_FOUND',
  WORKSPACE_LIMITED = 'WORKSPACE_LIMITED',
  WORKSPACE_NAME_IS_NOT_ALLOWED = 'WORKSPACE_NAME_IS_NOT_ALLOWED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  USER_WORKSPACE_NOT_FOUND = 'USER_WORKSPACE_NOT_FOUND',
  // SESSION_EXPIRED = 'USER_WORKSPACE_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  MOLECULER_NOT_REGISTER = 'MOLECULER_NOT_REGISTER',
  USER_NOT_ACTIVED = 'USER_NOT_ACTIVED',
  PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH',
  CONFIG_NOT_FOUND = 'CONFIG_NOT_FOUND',
  CACHE_SERVER_NOT_FOUND = 'CACHE_SERVER_NOT_FOUND',
  CODE_INVITE_NOT_FOUND = 'CODE_INVITE_NOT_FOUND',
  ACCOUNT_NOT_ACTIVE = 'ACCOUNT_NOT_ACTIVE',
  NOT_CENSOR_REQUEST_INVITE_EMAIL = 'NOT_CENSOR_REQUEST_INVITE_EMAIL',
  PHONE_NUMBER_DUPLICATED = 'PHONE_NUMBER_DUPLICATED',
  EMAIL_DUPLICATED = 'EMAIL_DUPLICATED',
  LIST_DEVICE_TOKEN_INVALID = 'LIST_DEVICE_TOKEN_INVALID',
  DEVICE_TOKEN_INVALID = 'DEVICE_TOKEN_INVALID',
  TOPIC_INVALID = 'TOPIC_INVALID',
  OLD_PASSWORD_IS_NOT_THE_SAME_WITH_NEW_PASSWORD = 'OLD_PASSWORD_IS_NOT_THE_SAME_WITH_NEW_PASSWORD',
  NEW_PASSWORD_NOT_MATCH = 'NEW_PASSWORD_NOT_MATCH',
  CANNOT_CHANGE_PASSWORD_OF_LOGIN_TYPE = 'CANNOT_CHANGE_PASSWORD_OF_LOGIN_TYPE',
  SERVER_ERROR = 'SERVER_ERROR',
  PERMISSION_MIDDLEWARE_DENIED_CUSTOM_JOB_POSITION = 'PERMISSION_MIDDLEWARE_DENIED_CUSTOM_JOB_POSITION',
  LOGIN_WRONG_PROVIDER = 'LOGIN_WRONG_PROVIDER',
  PERMISSION_DENIED_STAFF_TYPE_AND_ALL_SCOPE = 'PERMISSION_DENIED_STAFF_TYPE_AND_ALL_SCOPE',
  WORKSPACE_PACKAGE_EXPIRED = 'WORKSPACE_PACKAGE_EXPIRED',
  REACH_LIMIT_USER_WORKSPACE = 'REACH_LIMIT_USER_WORKSPACE',
  REQUEST_CALLBACK_TOO_MUCH = 'REQUEST_CALLBACK_TOO_MUCH',
  SIGNATURE_INVALID = 'SIGNATURE_INVALID',
  FEATURE_PERMISSION_DENIED = 'FEATURE_PERMISSION_DENIED',
  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  CANNOT_GET_STATISTIC_IN_FUTURE = 'CANNOT_GET_STATISTIC_IN_FUTURE',
  CANNOT_INITIAL_WORKSPACE_DATA = 'CANNOT_INITIAL_WORKSPACE_DATA',

  /**
   * otm - 1200 -> 1300
   */
  SHIFT_TIME_INPUT_INVALID = 'SHIFT_TIME_INPUT_INVALID',
  SHIFT_WEEKDAY_REQUIRE = 'SHIFT_WEEKDAY_REQUIRE',

  /**
   * COURSE ERROR 1300 --> 1399
   */
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  CLASSROOM_NOT_FOUND = 'CLASSROOM_NOT_FOUND',
  CLASS_NOT_FOUND = 'CLASS_NOT_FOUND',
  SCORE_INVALID = 'SCORE_INVALID',
  EVALUATION_NOT_FOUND = 'EVALUATION_NOT_FOUND',
  EVALUATION_OPTION_NOT_FOUND = 'EVALUATION_OPTION_NOT_FOUND',

  /**
   * * Organization
   */
  ORGANIZATION_USER_INVALID = 'ORGANIZATION_USER_INVALID',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  CAN_NOT_REMOVE_PARENT_ORGANIZATION = 'CAN_NOT_REMOVE_PARENT_ORGANIZATION',
  REMOVE_ORGANIZATION_NEED_TO_REMOVE_USER_WORKSPACE_ORGANIZATION = 'REMOVE_ORGANIZATION_NEED_TO_REMOVE_USER_WORKSPACE_ORGANIZATION',
  OBJECT_NOT_VALID = 'OBJECT_NOT_VALID',
  ORGANIZATION_IS_EXIST = 'ORGANIZATION_IS_EXIST',
  ORGANIZATION_CODE_IS_EXIST = 'ORGANIZATION_CODE_IS_EXIST',
  ORGANIZATION_NAME_IS_EXIST = 'ORGANIZATION_NAME_IS_EXIST',
  ORGANIZATION_MAIN_MANAGER_NOT_FOUND = 'ORGANIZATION_MAIN_MANAGER_NOT_FOUND',
  CREATE_ORGANIZATION_PERMISSION_DENIED = 'CREATE_ORGANIZATION_PERMISSION_DENIED',
  UPDATE_ORGANIZATION_PERMISSION_DENIED = 'UPDATE_ORGANIZATION_PERMISSION_DENIED',
  DELETE_ORGANIZATION_PERMISSION_DENIED = 'DELETE_ORGANIZATION_PERMISSION_DENIED',
  MANAGER_NOT_FOUND = 'MANAGER_NOT_FOUND',

  /**
   * * User Workspace Organization
   */
  USER_WORKSPACE_ORGANIZATION_INVALID = 'USER_WORKSPACE_ORGANIZATION_INVALID',
  USER_WORKSPACE_ORGANIZATION_EXISTED = 'USER_WORKSPACE_ORGANIZATION_EXISTED',
  INVITE_USER_TO_ORGANIZATION_SUCCESSFULLY = 'INVITE_USER_TO_ORGANIZATION_SUCCESSFULLY',
  USER_WORKSPACE_ORGANIZATION_CHANGE_ORGANIZATION = 'USER_WORKSPACE_ORGANIZATION_CHANGE_ORGANIZATION',
  USER_WORKSPACE_ORGANIZATION_NOT_FOUND = 'USER_WORKSPACE_ORGANIZATION_NOT_FOUND',
  CREATE_USER_WORKSPACE_ORGANIZATION_PERMISSION_DENIED = 'CREATE_USER_WORKSPACE_ORGANIZATION_PERMISSION_DENIED',
  UPDATE_USER_WORKSPACE_ORGANIZATION_PERMISSION_DENIED = 'UPDATE_USER_WORKSPACE_ORGANIZATION_PERMISSION_DENIED',
  DELETE_USER_WORKSPACE_ORGANIZATION_PERMISSION_DENIED = 'DELETE_USER_WORKSPACE_ORGANIZATION_PERMISSION_DENIED',
  CHANGE_USER_WORKSPACE_ORGANIZATION_PERMISSION_DENIED = 'CHANGE_USER_WORKSPACE_ORGANIZATION_PERMISSION_DENIED',
  EXPORT_STAFF_BY_ORGANIZATION_PERMISSION_DENIED = 'EXPORT_STAFF_BY_ORGANIZATION_PERMISSION_DENIED',
  CANNOT_HAVE_PERMISSION_TO_VIEW_THIS_ORGANIZATION = 'CANNOT_HAVE_PERMISSION_TO_VIEW_THIS_ORGANIZATION',

  /**
   * * User Invite Config
   */
  USER_INVITE_CONFIG_NOT_FOUND = 'USER_INVITE_CONFIG_NOT_FOUND',
  USER_INVITE_CONFIG_EXPIRED = 'USER_INVITE_CONFIG_EXPIRED',
  USER_INVITE_CONFIG_NOT_VALID = 'USER_INVITE_CONFIG_NOT_VALID',
  REQUIRE_USER_INVITE_LINK_EMAIL_OR_CONTACT_ADMIN = 'REQUIRE_USER_INVITE_LINK_EMAIL_OR_CONTACT_ADMIN',

  /**
   * * Workspace Invite Config
   */
  WORKSPACE_INVTE_CONFIG_NOT_FOUND = 'WORKSPACE_INVTE_CONFIG_NOT_FOUND',

  /**
   * * User Workspace
   */
  USER_WORKSPACE_EXISTED = 'USER_WORKSPACE_EXISTED',
  USER_WORKSPACE_STILL_WORKING = 'USER_WORKSPACE_STILL_WORKING',
  LEADER_NOT_FOUND = 'LEADER_NOT_FOUND',
  LIMIT_CHECKIN_IMAGES = 'LIMIT_CHECKIN_IMAGES',
  INVALID_END_WORK_DATE = 'INVALID_END_WORK_DATE',
  USER_WORKSPACE_IS_RETIRED_CONTEXT_CASE = 'USER_WORKSPACE_IS_RETIRED_CONTEXT_CASE',
  USER_WORKSPACE_IS_RETIRED_LOGIN_CASE = 'USER_WORKSPACE_IS_RETIRED_LOGIN_CASE',
  STAFF_CODE_IS_DUPLICATE = 'STAFF_CODE_IS_DUPLICATE',
  USER_WORKSPACE_IS_NOT_WORKSPACE_OWNER = 'USER_WORKSPACE_IS_NOT_WORKSPACE_OWNER',
  VIEW_USER_WORKSPACE_PERMISSION_DENIED = 'VIEW_USER_WORKSPACE_PERMISSION_DENIED',
  UPDATE_USER_WORKSPACE_PERMISSION_DENIED = 'UPDATE_USER_WORKSPACE_PERMISSION_DENIED',
  CANNOT_CHANGE_YOUR_WORKING_STATUS = 'CANNOT_CHANGE_YOUR_WORKING_STATUS',
  CANNOT_CHANGE_WORKSPACE_OWNER_WORKING_STATUS = 'CANNOT_CHANGE_WORKSPACE_OWNER_WORKING_STATUS',
  CAN_NOT_CHANGE_WORKSPACE_OWNER_TO_YOURSELF = 'CAN_NOT_CHANGE_WORKSPACE_OWNER_TO_YOURSELF',
  CHANGE_WORKING_STATUS_USER_WORKSPACE_PERMISSION_DENIED = 'CHANGE_WORKING_STATUS_USER_WORKSPACE_PERMISSION_DENIED',
  USER_WORKSPACE_WORK_PROGRESS_NOT_FOUND = 'USER_WORKSPACE_WORK_PROGRESS_NOT_FOUND',
  CAN_NOT_DELETE_OR_UPDATE_WORK_PROGRESS_TYPE_AUTO = 'CAN_NOT_DELETE_OR_UPDATE_WORK_PROGRESS_TYPE_AUTO',
  FROM_DATE_MUST_EQUAL_LESS_THAN_TO_DATE = 'FROM_DATE_MUST_EQUAL_LESS_THAN_TO_DATE',
  USER_WORKSPACE_WORK_PROGRESS_DUPLICATED = 'USER_WORKSPACE_WORK_PROGRESS_DUPLICATED',
  WORK_PROGRESS_WORKPLACE_CAN_NOT_EMPTY = 'WORK_PROGRESS_WORKPLACE_CAN_NOT_EMPTY',
  WORK_PROGRESS_JOB_POSITION_CAN_NOT_EMPTY = 'WORK_PROGRESS_JOB_POSITION_CAN_NOT_EMPTY',
  WORK_PROGRESS_MANUAL_MUST_EQUAL_SMALL_THAN_START_WORK_DATE = 'WORK_PROGRESS_MANUAL_MUST_EQUAL_SMALL_THAN_START_WORK_DATE',
  FROM_DATE_AND_TO_DATE_MUST_SAME_YEAR = 'FROM_DATE_AND_TO_DATE_MUST_SAME_YEAR',
  UPLOAD_EXCEED_LIMIT_CHECKIN_IMAGES = 'UPLOAD_EXCEED_LIMIT_CHECKIN_IMAGES',
  TO_DATE_MUST_EQUAL_LESS_THAN_ONE_MONTH = 'TO_DATE_MUST_EQUAL_LESS_THAN_ONE_MONTH',

  /**
   * * Group Permission
   */
  GROUP_PERMISSION_NOT_FOUND = 'GROUP_PERMISSION_NOT_FOUND',
  GROUP_PERMISSION_EXISTED = 'GROUP_PERMISSION_EXISTED',
  CREATE_GROUP_PERMISSION_DENIED = 'CREATE_GROUP_PERMISSION_DENIED',
  UPDATE_GROUP_PERMISSION_DENIED = 'UPDATE_GROUP_PERMISSION_DENIED',
  GROUP_PERMISSION_CAN_NOT_DELETE = 'GROUP_PERMISSION_CAN_NOT_DELETE',
  ONLY_OWNER_CAN_ADD_USER_TO_GROUP_SUPER_ADMIN = 'ONLY_OWNER_CAN_ADD_USER_TO_GROUP_SUPER_ADMIN',
  USER_WORKSPACE_ALREADY_SUPER_ADMIN = 'USER_WORKSPACE_ALREADY_SUPER_ADMIN',
  ONLY_OWNER_CAN_CHANGE_USER_TO_GROUP_SUPER_ADMIN = 'ONLY_OWNER_CAN_CHANGE_USER_TO_GROUP_SUPER_ADMIN',

  ONLY_OWNER_CAN_REMOVE_SUPER_ADMIN_USER = 'ONLY_OWNER_CAN_REMOVE_SUPER_ADMIN_USER',
  CAN_NOT_CHANGE_SUPER_ADMIN_USER_PERMISSION = 'CAN_NOT_CHANGE_SUPER_ADMIN_USER_PERMISSION',
  CAN_NOT_CHANGE_USER_TO_GROUP_ADMIN = 'CAN_NOT_CHANGE_USER_TO_GROUP_ADMIN',
  OWNER_CANNOT_REMOVE_ITSELF_FROM_GROUP_SUPER_ADMIN = 'OWNER_CANNOT_REMOVE_ITSELF_FROM_GROUP_SUPER_ADMIN',
  USER_CANNOT_REMOVE_SUPER_ADMIN_USER_PERMISSION = 'USER_CANNOT_REMOVE_SUPER_ADMIN_USER_PERMISSION',
  ONLY_YOU_CAN_REMOVE_YOURSELF_FROM_GROUP_SUPER_ADMIN = 'ONLY_YOU_CAN_REMOVE_YOURSELF_FROM_GROUP_SUPER_ADMIN',
  CUSTOM_ORGANIZATION_CAN_NOT_EMPTY = 'CUSTOM_ORGANIZATION_CAN_NOT_EMPTY',

  /**
   * * User Workspace Permission
   */
  USER_WORKSPACE_NOT_SUPER_ADMIN_CHANGE_OWNER = 'USER_WORKSPACE_NOT_SUPER_ADMIN_CHANGE_OWNER',
  USER_WORKSPACE_PERMISSION_NOT_FOUND = 'USER_WORKSPACE_PERMISSION_NOT_FOUND',
  CAN_NOT_CHANGE_GROUP_PERMISSION_OF_OWNER = 'CAN_NOT_CHANGE_GROUP_PERMISSION_OF_OWNER',

  /**
   * * Staff type
   */
  STAFF_TYPE_INVALID = 'STAFF_TYPE_INVALID',
  STAFF_TYPE_NOT_FOUND = 'STAFF_TYPE_NOT_FOUND',
  STAFF_TYPE_IS_EXIST = 'STAFF_TYPE_IS_EXIST',
  STAFF_TYPE_CANNOT_UPDATE = 'STAFF_TYPE_CANNOT_UPDATE',
  CANNOT_REMOVE_ACTIVE_STAFF_TYPE = 'CANNOT_REMOVE_ACTIVE_STAFF_TYPE',
  CANNOT_REMOVE_OR_INACTIVE_DEFAULT_STAFF_TYPE = 'CANNOT_REMOVE_OR_INACTIVE_DEFAULT_STAFF_TYPE',

  /**
   * * Health facility
   */
  HEALTH_FACILITY_INVALID = 'HEALTH_FACILITY_INVALID',
  HEALTH_FACILITY_NOT_FOUND = 'HEALTH_FACILITY_NOT_FOUND',
  HEALTH_FACILITY_IS_EXIST = 'HEALTH_FACILITY_IS_EXIST',
  HEALTH_FACILITY_CANNOT_UPDATE = 'HEALTH_FACILITY_CANNOT_UPDATE',
  HEALTH_FACILITY_TYPE_INVALID = 'HEALTH_FACILITY_TYPE_INVALID',
  HEALTH_FACILITY_TYPE_NOT_FOUND = 'HEALTH_FACILITY_TYPE_NOT_FOUND',
  HEALTH_FACILITY_TYPE_IS_EXIST = 'HEALTH_FACILITY_TYPE_IS_EXIST',
  HEALTH_FACILITY_TYPE_CANNOT_UPDATE = 'HEALTH_FACILITY_TYPE_CANNOT_UPDATE',
  HEALTH_EXAMINATION_DATE_INVALID = 'HEALTH_EXAMINATION_DATE_INVALID',
  HEALTH_EXAMINATION_INVALID = 'HEALTH_EXAMINATION_INVALID',
  HEALTH_EXAMINATION_NOT_FOUND = 'HEALTH_EXAMINATION_NOT_FOUND',
  HEALTH_EXAMINATION_IS_EXIST = 'HEALTH_EXAMINATION_IS_EXIST',
  HEALTH_EXAMINATION_CANNOT_UPDATE = 'HEALTH_EXAMINATION_CANNOT_UPDATE',

  /**
   * * Job title
   */
  JOB_TITLE_GROUP_INVALID = 'JOB_TITLE_GROUP_INVALID',
  JOB_TITLE_GROUP_NOT_FOUND = 'JOB_TITLE_GROUP_NOT_FOUND',
  JOB_TITLE_GROUP_IS_EXIST = 'JOB_TITLE_GROUP_IS_EXIST',
  JOB_TITLE_GROUP_CANNOT_UPDATE = 'JOB_TITLE_GROUP_CANNOT_UPDATE',
  JOB_TITLE_INVALID = 'JOB_TITLE_INVALID',
  JOB_TITLE_NOT_FOUND = 'JOB_TITLE_NOT_FOUND',
  JOB_TITLE_IS_EXIST = 'JOB_TITLE_IS_EXIST',
  JOB_TITLE_CANNOT_UPDATE = 'JOB_TITLE_CANNOT_UPDATE',

  /**
   * * Material compensation
   */
  MATERIAL_INVALID = 'MATERIAL_INVALID',
  MATERIAL_NOT_FOUND = 'MATERIAL_NOT_FOUND',
  MATERIAL_IS_EXIST = 'MATERIAL_IS_EXIST',
  MATERIAL_CANNOT_UPDATE = 'MATERIAL_CANNOT_UPDATE',
  MATERIAL_COMPENSATION_INVALID = 'MATERIAL_COMPENSATION_INVALID',
  MATERIAL_COMPENSATION_NOT_FOUND = 'MATERIAL_COMPENSATION_NOT_FOUND',
  MATERIAL_COMPENSATION_IS_EXIST = 'MATERIAL_COMPENSATION_IS_EXIST',
  MATERIAL_COMPENSATION_CANNOT_UPDATE = 'MATERIAL_COMPENSATION_CANNOT_UPDATE',

  /*
   * * Reward Title Type
   */
  REWARD_TITLE_TYPE_NOT_FOUND = 'REWARD_TITLE_TYPE_NOT_FOUND',
  CAN_NOT_DELETE_ACTIVE_REWARD_TITLE_TYPE = 'CAN_NOT_DELETE_ACTIVE_REWARD_TITLE_TYPE',
  REWARD_TITLE_TYPE_CODE_EXISTED = 'REWARD_TITLE_TYPE_CODE_EXISTED',
  CAN_NOT_DELETE_REWARD_TITLE_TYPES_HAS_RELATION_INFORMATION_EXISTED = 'CAN_NOT_DELETE_REWARD_TITLE_TYPES_HAS_RELATION_INFORMATION_EXISTED',

  /*
   * * Reward Title
   */
  REWARD_TITLE_NOT_FOUND = 'REWARD_TITLE_NOT_FOUND',
  CAN_NOT_DELETE_ACTIVE_REWARD_TITLE = 'CAN_NOT_DELETE_ACTIVE_REWARD_TITLE',
  REWARD_TITLE_CODE_EXISTED = 'REWARD_TITLE_CODE_EXISTED',
  CAN_NOT_UPDATE_DISCIPLINE_HAS_RELATION_DATA = 'CAN_NOT_UPDATE_DISCIPLINE_HAS_RELATION_DATA',
  CAN_NOT_UPDATE_DISCIPLINE_BEHAVIOR_HAS_RELATION_DATA = 'CAN_NOT_UPDATE_DISCIPLINE_BEHAVIOR_HAS_RELATION_DATA',
  CAN_NOT_UPDATE_REWARD_TITLE_HAS_RELATION_DATA = 'CAN_NOT_UPDATE_REWARD_TITLE_HAS_RELATION_DATA',
  CAN_NOT_UPDATE_REWARD_TITLE_TYPE_HAS_RELATION_DATA = 'CAN_NOT_UPDATE_REWARD_TITLE_TYPE_HAS_RELATION_DATA',

  /*
   * * Reward Decision
   */
  REWARD_DECISION_NOT_FOUND = 'REWARD_DECISION_NOT_FOUND',
  CAN_NOT_DELETE_OR_UPDATE_APPROVED_REWARD_DECISION = 'CAN_NOT_DELETE_OR_UPDATE_APPROVED_REWARD_DECISION',
  REWARD_DECISION_NUMBER_EXISTED = 'REWARD_DECISION_NUMBER_EXISTED',
  APPLICABLE_GROUP_REWARD_CAN_NOT_EMPTY = 'APPLICABLE_GROUP_REWARD_CAN_NOT_EMPTY',
  APPLICABLE_INDIVIDUAL_REWARD_CAN_NOT_EMPTY = 'APPLICABLE_INDIVIDUAL_REWARD_CAN_NOT_EMPTY',

  /*
   * * Discipline Decision
   */
  DISCIPLINE_DECISION_NOT_FOUND = 'DISCIPLINE_DECISION_NOT_FOUND',
  CAN_NOT_DELETE_OR_UPDATE_APPROVED_DISCIPLINE_DECISION = 'CAN_NOT_DELETE_OR_UPDATE_APPROVED_DISCIPLINE_DECISION',
  DISCIPLINE_DECISION_NUMBER_EXISTED = 'DISCIPLINE_DECISION_NUMBER_EXISTED',
  APPLICABLE_GROUP_DISCIPLINE_CAN_NOT_EMPTY = 'APPLICABLE_GROUP_DISCIPLINE_CAN_NOT_EMPTY',
  APPLICABLE_INDIVIDUAL_DISCIPLINE_CAN_NOT_EMPTY = 'APPLICABLE_INDIVIDUAL_DISCIPLINE_CAN_NOT_EMPTY',

  /*
   * * Discipline
   */
  DISCIPLINE_NOT_FOUND = 'DISCIPLINE_NOT_FOUND',
  CAN_NOT_DELETE_ACTIVE_DISCIPLINE = 'CAN_NOT_DELETE_ACTIVE_DISCIPLINE',
  DISCIPLINE_CODE_EXISTED = 'DISCIPLINE_CODE_EXISTED',

  /*
   * * Discipline Behavior
   */
  DISCIPLINE_BEHAVIOR_NOT_FOUND = 'DISCIPLINE_BEHAVIOR_NOT_FOUND',
  CAN_NOT_DELETE_ACTIVE_DISCIPLINE_BEHAVIOR = 'CAN_NOT_DELETE_ACTIVE_DISCIPLINE_BEHAVIOR',
  DISCIPLINE_BEHAVIOR_CODE_EXISTED = 'DISCIPLINE_BEHAVIOR_CODE_EXISTED',

  /*
   * * Insurance
   */
  INSURANCE_NOT_FOUND = 'INSURANCE_NOT_FOUND',
  CAN_NOT_DELETE_ACTIVE_INSURANCE = 'CAN_NOT_DELETE_ACTIVE_INSURANCE',
  INSURANCE_CODE_EXISTED = 'INSURANCE_CODE_EXISTED',

  /**
   * * Bank
   */
  BANK_CODE_EXISTED = 'BANK_CODE_EXISTED',
  BANK_NOT_FOUND = 'BANK_NOT_FOUND',
  CAN_NOT_DELETE_BANK_HAS_RELATION_INFORMATION_EXISTED = 'CAN_NOT_DELETE_BANK_HAS_RELATION_INFORMATION_EXISTED',
  CAN_NOT_INACTIVE_BANK_HAS_RELATION_INFORMATION_EXISTED = 'CAN_NOT_INACTIVE_BANK_HAS_RELATION_INFORMATION_EXISTED',
  CAN_NOT_DELETE_ACTIVE_BANK = 'CAN_NOT_DELETE_ACTIVE_BANK',

  /**
   * * Bank Branch
   */
  BANK_BRANCH_NOT_FOUND = 'BANK_BRANCH_NOT_FOUND',
  BANK_BRANCH_CODE_IS_EXIST = 'BANK_BRANCH_CODE_IS_EXIST',
  BANK_BRANCH_NAME_EXISTED = 'BANK_BRANCH_NAME_EXISTED',
  CAN_NOT_DELETE_ACTIVE_BANK_BRANCH = 'CAN_NOT_DELETE_ACTIVE_BANK_BRANCH',
  CAN_NOT_DELETE_BANK_BRANCH_HAS_RELATION_INFORMATION_EXISTED = 'CAN_NOT_DELETE_BANK_BRANCH_HAS_RELATION_INFORMATION_EXISTED',
  CAN_NOT_INACTIVE_BANK_BRANCH_HAS_RELATION_INFORMATION_EXISTED = 'CAN_NOT_INACTIVE_BANK_BRANCH_HAS_RELATION_INFORMATION_EXISTED',

  /**
   * * User Workspace Bank Account
   */
  USER_WORKSPACE_BANK_ACCOUNT_NOT_FOUND = 'USER_WORKSPACE_BANK_ACCOUNT_NOT_FOUND',
  CAN_NOT_DELETE_SALARY_BANK_ACCOUNT = 'CAN_NOT_DELETE_SALARY_BANK_ACCOUNT',
  ALREADY_HAVE_SALARY_BANK_ACCOUNT = 'ALREADY_HAVE_SALARY_BANK_ACCOUNT',
  CHANGE_ALREADY_HAVE_SALARY_BANK_ACCOUNT = 'CHANGE_ALREADY_HAVE_SALARY_BANK_ACCOUNT',

  /*
   * * User Workspace Personal Tax
   */
  USER_WORKSPACE_PERSONAL_TAX_NOT_FOUND = 'USER_WORKSPACE_PERSONAL_TAX_NOT_FOUND',
  USER_WORKSPACE_PERSONAL_TAX_CODE_EXISTED = 'USER_WORKSPACE_PERSONAL_TAX_CODE_EXISTED',
  USER_WORKSPACE_PERSONAL_TAX_EXISTED = 'USER_WORKSPACE_PERSONAL_TAX_EXISTED',

  /**
   * * Other
   */
  DUPLICATE_HOST = 'DUPLICATE_HOST',
  ONLY_ALLOW_EXCEL_FILE = 'ONLY_ALLOW_EXCEL_FILE',
  FILE_IMPORT_FORMAT_INCORRECT = 'FILE_IMPORT_FORMAT_INCORRECT',
  GOOGLEAPI_EMAIL_NOT_FOUND = 'GOOGLEAPI_EMAIL_NOT_FOUND',
  GOOGLEAPI_ACCESS_TOKEN_EXPIRED = 'GOOGLEAPI_ACCESS_TOKEN_EXPIRED',
  GOOGLEAPI_CREDIENTIAL_FAILED = 'GOOGLEAPI_CREDIENTIAL_FAILED',
  FACEBOOK_ACCESS_TOKEN_INVALID = 'FACEBOOK_ACCESS_TOKEN_INVALID',
  FACEBOOK_EMAIL_NOT_FOUND = 'FACEBOOK_EMAIL_NOT_FOUND',
  APPLE_ACCESS_TOKEN_INVALID = 'APPLE_ACCESS_TOKEN_INVALID',
  USER_APPLE_ID_NOT_FOUND = 'USER_APPLE_ID_NOT_FOUND',
  ACCESS_TOKEN_NOT_VALID = 'ACCESS_TOKEN_NOT_VALID',
  EXPIRES_DATE_MUST_EQUAL_LARGER_THAN_NOW = 'EXPIRES_DATE_MUST_EQUAL_LARGER_THAN_NOW',
  EXPIRES_DATE_MUST_EQUAL_LARGER_THAN_VALID_DATE = 'EXPIRES_DATE_MUST_EQUAL_LARGER_THAN_VALID_DATE',
  USER_FACEBOOK_ID_NOT_FOUND = 'USER_FACEBOOK_ID_NOT_FOUND',

  /**
   * * Permission
   */
  PERMISSION_MIDDLEWARE_DENIED = 'PERMISSION_MIDDLEWARE_DENIED',
  PERMISSION_MIDDLEWARE_DENIED_CUSTOM = 'PERMISSION_MIDDLEWARE_DENIED_CUSTOM',
  PERMISSION_MIDDLEWARE_DENIED_CUSTOM_OR_ORPERATOR = 'PERMISSION_MIDDLEWARE_DENIED_CUSTOM_OR_ORPERATOR',
  PERMISSION_MIDDLEWARE_CUSTOM_ACTION_TEXT = 'PERMISSION_MIDDLEWARE_CUSTOM_ACTION_TEXT',

  /**
   * Job position
   */
  JOB_POSITION_HAS_ALREADY_EXISTED = 'JOB_POSITION_HAS_ALREADY_EXISTED',
  JOB_POSITION_NOT_FOUND = 'JOB_POSITION_NOT_FOUND',
  USER_WORKSPACE_JOB_POSITION_NOT_FOUND = 'USER_WORKSPACE_JOB_POSITION_NOT_FOUND',
  USER_WORKSPACE_JOB_POSITION_HAS_ALREADY_EXISTED = 'USER_WORKSPACE_JOB_POSITION_HAS_ALREADY_EXISTED',
  INVALID_EXPIRES_DATE = 'INVALID_EXPIRES_DATE',
  INVALID_VALID_DATE = 'INVALID_VALID_DATE',
  JOB_POSITION_ROLE_NOT_VALID = 'JOB_POSITION_ROLE_NOT_VALID',
  ONLY_ALLOW_ONE_HEAD_MANAGER_JOB_POSITION = 'ONLY_ALLOW_ONE_HEAD_MANAGER_JOB_POSITION',
  ONLY_ALLOW_ONE_SUB_MANAGER_JOB_POSITION = 'ONLY_ALLOW_ONE_SUB_MANAGER_JOB_POSITION',
  HAS_STAFF_IN_JOB_POSITION = 'HAS_STAFF_IN_JOB_POSITION',
  NOT_ALLOW_TO_REMOVE_MANAGER_JOB_POSITION = 'NOT_ALLOW_TO_REMOVE_MANAGER_JOB_POSITION',

  /**
   * * Coefficient
   */
  COEFFICIENT_CODE_IS_EXIST = 'COEFFICIENT_CODE_IS_EXIST',
  COEFFICIENT_CODE_NOT_FOUND = 'COEFFICIENT_CODE_NOT_FOUND',
  COEFFICIENT_CODE_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED = 'COEFFICIENT_CODE_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED',
  COEFFICIENT_CODE_ACTIVE = 'COEFFICIENT_CODE_ACTIVE',

  /**
   * * Coefficient Region
   */
  COEFFICIENT_REGION_CODE_IS_EXIST = 'COEFFICIENT_REGION_CODE_IS_EXIST',
  COEFFICIENT_CODE_REGION_NOT_FOUND = 'COEFFICIENT_CODE_REGION_NOT_FOUND',
  COEFFICIENT_CODE_REGION_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED = 'COEFFICIENT_CODE_REGION_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED',
  COEFFICIENT_REGION_CODE_ACTIVE = 'COEFFICIENT_REGION_CODE_ACTIVE',
  EXPIRES_DATE_CAN_NOT_LESS_THAN_NOW = 'EXPIRES_DATE_CAN_NOT_LESS_THAN_NOW',
  EXPIRES_DATE_CAN_NOT_LESS_THAN_VALID_DATE = 'EXPIRES_DATE_CAN_NOT_LESS_THAN_VALID_DATE',
  COEFFICIENT_REGION_IS_EXIST = 'COEFFICIENT_REGION_IS_EXIST',

  /**
   * * locations
   */
  COUNTRY_NOT_FOUND = 'COUNTRY_NOT_FOUND',
  REGION_NOT_FOUND = 'REGION_NOT_FOUND',
  CITY_NOT_FOUND = 'CITY_NOT_FOUND',
  DISTRICT_NOT_FOUND = 'DISTRICT_NOT_FOUND',
  WARD_NOT_FOUND = 'WARD_NOT_FOUND',

  /**
   * * Occupations
   */
  UNIVERSITY_CODE_NOT_FOUND = 'UNIVERSITY_CODE_NOT_FOUND',
  UNIVERSITY_CODE_IS_EXIST = 'UNIVERSITY_CODE_IS_EXIST',
  UNIVERSITY_CODE_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED = 'UNIVERSITY_CODE_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED',
  MAJOR_CODE_NOT_FOUND = 'MAJOR_CODE_NOT_FOUND',
  MAJOR_CODE_IS_EXIST = 'MAJOR_CODE_IS_EXIST',
  MAJOR_CODE_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED = 'MAJOR_CODE_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED',
  OCCUPATION_CODE_NOT_FOUND = 'OCCUPATION_CODE_NOT_FOUND',
  OCCUPATION_CODE_IS_EXIST = 'OCCUPATION_CODE_IS_EXIST',
  OCCUPATION_CODE_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED = 'OCCUPATION_CODE_CANNOT_REMOVE_HAS_RELATION_INFORMATION_EXISTED',
  INVALID_UNIVERSITY_DATA = 'INVALID_UNIVERSITY_DATA',
  INVALID_OCCUPATION_DATA = 'INVALID_OCCUPATION_DATA',

  /**
   * *  user workspace trainings
   */
  USER_WORKSPACE_TRAINING_CODE_NOT_FOUND = 'USER_WORKSPACE_TRAINING_CODE_NOT_FOUND',
  END_DATE_TRAINING_MUST_EQUAL_LARGER_THAN_START_DATE_TRAINING = 'END_DATE_TRAINING_MUST_EQUAL_LARGER_THAN_START_DATE_TRAINING',
  DIPLOMA_RETURN_DATE_MUST_EQUAL_LARGER_THAN_DIPLOMA_SUBMISSION_DATE = 'DIPLOMA_RETURN_DATE_MUST_EQUAL_LARGER_THAN_DIPLOMA_SUBMISSION_DATE',

  /**
   * * ALLOWANCE
   */
  ALLOWANCE_TYPE_IS_EXISTED = 'ALLOWANCE_TYPE_IS_EXISTED',
  ALLOWANCE_TYPE_NOT_FOUND = 'ALLOWANCE_TYPE_NOT_FOUND',
  ALLOWANCE_IS_EXISTED = 'ALLOWANCE_IS_EXISTED',
  ALLOWANCE_NOT_FOUND = 'ALLOWANCE_NOT_FOUND',
  CAN_NOT_DELETE_ALLOWANCE_TYPE = 'CAN_NOT_DELETE_ALLOWANCE_TYPE',
  CAN_NOT_DELETE_ALLOWANCE = 'CAN_NOT_DELETE_ALLOWANCE',
  USER_WORKSPACE_ALLOWANCE_NOT_FOUND = 'USER_WORKSPACE_ALLOWANCE_NOT_FOUND',
  CANNOT_DELTE_USER_WORKSPACE_ALLOWANCE = 'CANNOT_DELTE_USER_WORKSPACE_ALLOWANCE',
  USER_WORKSPACE_ALLOWANCE_EXISTED = 'USER_WORKSPACE_ALLOWANCE_EXISTED',
  USER_WORKSPACE_ALLOWANCE_EXPIRED = 'USER_WORKSPACE_ALLOWANCE_EXPIRED',
  USER_WORKSPACE_ALLOWANCE_EXPIRES_TODAY = 'USER_WORKSPACE_ALLOWANCE_EXPIRES_TODAY',
  VALID_EXPIRES_DATE_MUST_LARGER_EQUAL_THAN_CURRENT_SALARY_PERIOD = 'VALID_EXPIRES_DATE_MUST_LARGER_EQUAL_THAN_CURRENT_SALARY_PERIOD',
  CUSTOM_USER_WORKSPACE_ALLOWANCE_EXISTED = 'CUSTOM_USER_WORKSPACE_ALLOWANCE_EXISTED',
  CANNOT_UPDATE_USER_WORKSPACE_ALLOWANCE_APPLIED_IN_THE_PAST = 'CANNOT_UPDATE_USER_WORKSPACE_ALLOWANCE_APPLIED_IN_THE_PAST',
  CANNOT_UPDATE_VALID_DATE_OF_USER_WORKSPACE_ALLOWANCE_APPLIED_IN_THE_PAST = 'CANNOT_UPDATE_VALID_DATE_OF_USER_WORKSPACE_ALLOWANCE_APPLIED_IN_THE_PAST',
  ONLY_ALLOW_CHANGE_EXPIRES_DATE_FOR_USER_WORKSPACE_ALLOWANCE_IN_THE_PAST = 'ONLY_ALLOW_CHANGE_EXPIRES_DATE_FOR_USER_WORKSPACE_ALLOWANCE_IN_THE_PAST',
  CANNOT_REMOVE_APPLIED_USER_WORKSPACE_ALLOWANCE = 'CANNOT_REMOVE_APPLIED_USER_WORKSPACE_ALLOWANCE',
  NOT_CREATE_USER_WORKSPACE_ALLOWANCE_IN_PAST = 'NOT_CREATE_USER_WORKSPACE_ALLOWANCE_IN_PAST',

  /**
   * * Family Relation
   */
  FAMILY_RELATION_CODE_EXISTED = 'FAMILY_RELATION_CODE_EXISTED',
  FAMILY_RELATION_NOT_FOUND = 'FAMILY_RELATION_NOT_FOUND',
  USER_WORKSPACE_FAMILY_RELATION_YEAR_OF_BIRTH_INVALID = 'USER_WORKSPACE_FAMILY_RELATION_YEAR_OF_BIRTH_INVALID',
  USER_WORKSPACE_FAMILY_RELATION_INVALID = 'USER_WORKSPACE_FAMILY_RELATION_INVALID',
  USER_WORKSPACE_FAMILY_RELATION_NOT_FOUND = 'USER_WORKSPACE_FAMILY_RELATION_NOT_FOUND',
  USER_WORKSPACE_FAMILY_RELATION_IS_EXIST = 'USER_WORKSPACE_FAMILY_RELATION_IS_EXIST',
  USER_WORKSPACE_FAMILY_RELATION_CANNOT_UPDATE = 'USER_WORKSPACE_FAMILY_RELATION_CANNOT_UPDATE',
  DEPENDENT_FROM_TIME_IS_REQUIRED = 'DEPENDENT_FROM_TIME_IS_REQUIRED',
  DEPENDENT_TO_TIME_ERROR = 'DEPENDENT_TO_TIME_ERROR',

  /**
   * * 3rd Services
   */
  ID_SERVICES_ERROR = 'ID_SERVICES_ERROR',
  ID_SERVICES_ERROR_PASSWORD = 'ID_SERVICES_ERROR_PASSWORD',
  ACHECKIN_SERVICES_ERROR = 'ACHECKIN_SERVICES_ERROR',
  INSIDE_SERVICE_ERROR = 'INSIDE_SERVICE_ERROR',
  PROJECT_MANAGEMENT_ERROR = 'PROJECT_MANAGEMENT_ERROR',
  UPLOAD_CHECKIN_IMAGE_FAILED = 'UPLOAD_CHECKIN_IMAGE_FAILED',

  /**
   * * Separator
   */
  SEPARATOR_AND = 'SEPARATOR_AND',
  SEPARATOR_OR = 'SEPARATOR_OR',

  /**
   * * Labor contract
   */
  LABOR_CONTRACT_NOT_EXIST = 'LABOR_CONTRACT_NOT_EXIST',
  LABOR_CONTRACT_EXISTED = 'LABOR_CONTRACT_EXISTED',
  LABOR_CONTRACT_SIGN_DATE_INVALID = 'LABOR_CONTRACT_SIGN_DATE_INVALID',
  LABOR_CONTRACT_EFFECT_DATE_INVALID = 'LABOR_CONTRACT_EFFECT_DATE_INVALID',
  LABOR_CONTRACT_EXPIRES_DATE_INVALID = 'LABOR_CONTRACT_EXPIRES_DATE_INVALID',
  CAN_NOT_DELETE_LABOR_CONTRACT_WHEN_ACTIVE = 'CAN_NOT_DELETE_LABOR_CONTRACT_WHEN_ACTIVE',
  CAN_NOT_DELETE_LABOR_CONTRACT_WHEN_HAVE_USER = 'CAN_NOT_DELETE_LABOR_CONTRACT_WHEN_HAVE_USER',
  CAN_NOT_CHANGE_STATUS_LABOR_CONTRACT_WHEN_HAVE_USER = 'CAN_NOT_CHANGE_STATUS_LABOR_CONTRACT_WHEN_HAVE_USER',
  CAN_NOT_UPDATE_LABOR_CONTRACT_WHEN_HAVE_USER = 'CAN_NOT_UPDATE_LABOR_CONTRACT_WHEN_HAVE_USER',
  LABOR_CONTRACT_EFFECT_DATE_IN_SALARY_PERIOD = 'LABOR_CONTRACT_EFFECT_DATE_IN_SALARY_PERIOD',
  LABOR_CONTRACT_TEMPLATE_URL_NOT_EXIST = 'LABOR_CONTRACT_TEMPLATE_URL_NOT_EXIST',
  CAN_NOT_CREATE_NOTIFICATION_LABOR_CONTRACT_EXPIRE = 'CAN_NOT_CREATE_NOTIFICATION_LABOR_CONTRACT_EXPIRE',
  LABOR_CONTRACT_EXPIRE_NOT_FOUND = 'LABOR_CONTRACT_EXPIRE_NOT_FOUND',
  CANNOT_UPDATE_LABOR_CONTRACT_IN_PAST_SALARY_PERIOD = 'CANNOT_UPDATE_LABOR_CONTRACT_IN_PAST_SALARY_PERIOD',

  /**
   * * User workspace labor contract
   */
  USER_WORKSPACE_LABOR_CONTRACT_NOT_FOUND = 'USER_WORKSPACE_LABOR_CONTRACT_NOT_FOUND',
  USER_WORKSPACE_LABOR_CONTRACT_EXISTED = 'USER_WORKSPACE_LABOR_CONTRACT_EXISTED',
  LABOR_CONTRACR_ACTIVE_DUPLICATE = 'LABOR_CONTRACR_ACTIVE_DUPLICATE',
  USER_WORKSPACE_LABOR_CONTRACT_DUPLICATE_TIME = 'USER_WORKSPACE_LABOR_CONTRACT_DUPLICATE_TIME',
  CAN_NOT_REMOVE_USER_LABOR_CONTRACT_ACTIVE = 'CAN_NOT_REMOVE_USER_LABOR_CONTRACT_ACTIVE',
  CAN_NOT_UPDATE_EXPIRE_LABOR_SMALLER_THAN_CURRENT_DATE = 'CAN_NOT_UPDATE_EXPIRE_LABOR_SMALLER_THAN_CURRENT_DATE',
  LABOR_CONTRACT_NUMBER_DUPLICATED = 'LABOR_CONTRACT_NUMBER_DUPLICATED',
  ONLY_CHANGE_LABOR_CONTRACT_PENDING = 'ONLY_CHANGE_LABOR_CONTRACT_PENDING',
  NOT_CHANGE_LABOR_CONTRACT_EXPIRED = 'NOT_CHANGE_LABOR_CONTRACT_EXPIRED',
  NOT_CHANGE_LABOR_CONTRACT_DATE_GREATER_THAN_DATE_EXPRECT = 'NOT_CHANGE_LABOR_CONTRACT_DATE_GREATER_THAN_DATE_EXPRECT',
  CAN_NOT_UPDATE_CONTRACT_WHEN_HAVE_CONTRACT_ACTIVE = 'CAN_NOT_UPDATE_CONTRACT_WHEN_HAVE_CONTRACT_ACTIVE',
  NOT_CHANGE_INFO_IN_CONTRACT_ACTIVE = 'NOT_CHANGE_INFO_IN_CONTRACT_ACTIVE',
  NOT_CHANGE_EFFECT_DATE_OF_LABOR_CONTRACT_ACTIVE = 'NOT_CHANGE_EFFECT_DATE_OF_LABOR_CONTRACT_ACTIVE',
  NOT_CHANGE_LABOR_CONTRACT_ACTIVE = 'NOT_CHANGE_LABOR_CONTRACT_ACTIVE',
  SALARY_METHOD_CONFIG_RANK_IS_REQUIRED = 'SALARY_METHOD_CONFIG_RANK_IS_REQUIRED',
  NOT_REMOVE_LABOR_CONTRACT_EXPIRED = 'NOT_REMOVE_LABOR_CONTRACT_EXPIRED',

  /*
   * Category
   */
  ADMIN_NOT_ENABLE_ACTION_CATEGORY = 'ADMIN_NOT_ENABLE_ACTION_CATEGORY',

  /**
   * * User workspace social insurance
   */
  USER_WORKSPACE_SOCIAL_INSURANCE_NOT_FOUND = 'USER_WORKSPACE_SOCIAL_INSURANCE_NOT_FOUND',
  USER_WORKSPACE_SOCIAL_INSURANCE_EXISTED = 'USER_WORKSPACE_SOCIAL_INSURANCE_EXISTED',
  USER_WORKSPACE_HEALTH_INSURANCE_NOT_FOUND = 'USER_WORKSPACE_HEALTH_INSURANCE_NOT_FOUND',
  USER_WORKSPACE_HEALTH_INSURANCE_EXISTED = 'USER_WORKSPACE_HEALTH_INSURANCE_EXISTED',
  USER_WORKSPACE_INSURANCE_NOT_FOUND = 'USER_WORKSPACE_INSURANCE_NOT_FOUND',
  USER_WORKSPACE_INSURANCE_EXISTED = 'USER_WORKSPACE_INSURANCE_EXISTED',
  INSURANCE_START_DATE_MUST_EQUAL_LARGER_THAN_CONTRACT_SIGNING_DATE = 'INSURANCE_START_DATE_MUST_EQUAL_LARGER_THAN_CONTRACT_SIGNING_DATE',
  INSURANCE_END_DATE_MUST_LARGER_THAN_INSURANCE_START_DATE = 'INSURANCE_END_DATE_MUST_LARGER_THAN_INSURANCE_START_DATE',
  USER_WORKSPACE_LEAVE_SCOPES_NOT_FOUND = 'USER_WORKSPACE_LEAVE_SCOPES_NOT_FOUND',
  USER_WORKSPACE_LEAVE_STATISTIC_NOT_FOUND = 'USER_WORKSPACE_LEAVE_STATISTIC_NOT_FOUND',
  THE_REDUCED_BALANCE_CANNOT_BE_GREATER_THAN_THE_CURRENT_BALANCE = 'THE_REDUCED_BALANCE_CANNOT_BE_GREATER_THAN_THE_CURRENT_BALANCE',
  USER_WORKSPACE_LEAVE_BALANCE_NOT_ENOUGH = 'USER_WORKSPACE_LEAVE_BALANCE_NOT_ENOUGH',
  LEAVE_BALANCE_NOT_ENOUGH_TO_APPROVE = 'LEAVE_BALANCE_NOT_ENOUGH_TO_APPROVE',
  USER_WORKSPACE_LEAVE_BALANCE_EXPIRED = 'USER_WORKSPACE_LEAVE_BALANCE_EXPIRED',

  /**
   * * Leave type
   */
  LEAVE_RULE_TYPE_INVALID = 'LEAVE_RULE_TYPE_INVALID',
  LEAVE_SCOPE_SPECIFIED_NOT_FOUND = 'LEAVE_SCOPE_SPECIFIED_NOT_FOUND',
  LEAVE_SCOPE_STAFF_TYPE_NOT_FOUND = 'LEAVE_SCOPE_STAFF_TYPE_NOT_FOUND',
  LEAVE_TYPE_EXISTED = 'LEAVE_TYPE_EXISTED',
  LEAVE_TYPE_NOT_FOUND = 'LEAVE_TYPE_NOT_FOUND',
  NOT_ALLOW_TO_APPLY_IN_PAST = 'NOT_ALLOW_TO_APPLY_IN_PAST',
  USER_WORKSPACE_LEAVE_APPLIANCE_IS_EXIST = 'USER_WORKSPACE_LEAVE_APPLIANCE_IS_EXIST',
  CANNOT_SEND_APPLIANCE_IN_DAY_WITHOUT_SHIFT = 'CANNOT_SEND_APPLIANCE_IN_DAY_WITHOUT_SHIFT',
  ATTACH_FILE_IS_REQUIRED = 'ATTACH_FILE_IS_REQUIRED',
  CAN_NOT_CLAIM_LEAVE_TYPE_WORKING_DAY_WITH_TYPE_UNLIMITED = 'CAN_NOT_CLAIM_LEAVE_TYPE_WORKING_DAY_WITH_TYPE_UNLIMITED',
  LEAVE_TYPE_OVERTIME_EXISTED = 'LEAVE_TYPE_OVERTIME_EXISTED',
  LEAVE_TYPE_OVERTIME_NOT_FOUND = 'LEAVE_TYPE_OVERTIME_NOT_FOUND',
  LEAVE_TYPE_OVERTIME_BALANCE_NOT_ENOUGH = 'LEAVE_TYPE_OVERTIME_BALANCE_NOT_ENOUGH',

  /**
   * * User workspace leave type form
   */
  USER_WORKSPACE_LEAVE_TYPE_APPLIANCE_NOT_FOUND = 'USER_WORKSPACE_LEAVE_TYPE_APPLIANCE_NOT_FOUND',
  CANNOT_DELETE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE_IN_THE_PAST = 'CANNOT_DELETE_USER_WORKSPACE_LEAVE_TYPE_APPLIANCE_IN_THE_PAST',
  ALLOW_MIN_MAX_APPLIANCE = 'ALLOW_MIN_MAX_APPLIANCE',

  /**
   * * Approval
   */
  APPROVAL_GROUP_EXISTED = 'APPROVAL_GROUP_EXISTED',
  APPROVAL_GROUP_NOT_FOUND = 'APPROVAL_GROUP_NOT_FOUND',
  APPROVAL_EXISTED = 'APPROVAL_EXISTED',
  APPROVAL_NOT_FOUND = 'APPROVAL_NOT_FOUND',
  CAN_NOT_DELETE_APPROVAL_GROUP_HAS_APPROVAL_EXSITED = 'CAN_NOT_DELETE_APPROVAL_GROUP_HAS_APPROVAL_EXSITED',
  APPROVAL_GROUP_NAME_EXSITED = 'APPROVAL_GROUP_NAME_EXSITED',
  APPROVAL_NODE_EXISTED = 'APPROVAL_NODE_EXISTED',
  APPROVAL_NODE_NOT_FOUND = 'APPROVAL_NODE_NOT_FOUND',
  APPROVAL_LINE_EXISTED = 'APPROVAL_LINE_EXISTED',
  APPROVAL_LINE_NOT_FOUND = 'APPROVAL_LINE_NOT_FOUND',

  SELECT_SPECIFIC_LEVEL_FOR_THE_APPROVER = 'SELECT_SPECIFIC_LEVEL_FOR_THE_APPROVER',
  SELECT_GROUP_PERMISSION_FOR_THE_APPROVER = 'SELECT_GROUP_PERMISSION_FOR_THE_APPROVER',
  SELECT_USER_WORKSPACE_SPECIFIED_FOR_THE_APPROVAL = 'SELECT_USER_WORKSPACE_SPECIFIED_FOR_THE_APPROVAL',
  SELECT_METHOD_AND_SCOPE_FOR_THE_APPROVER = 'SELECT_METHOD_AND_SCOPE_FOR_THE_APPROVER',
  SELECT_USER_WORKSPACE_SPECIFIED_FOR_THE_APPROVAL_WHEN_APPROVER_IS_EMPTY = 'SELECT_USER_WORKSPACE_SPECIFIED_FOR_THE_APPROVAL_WHEN_APPROVER_IS_EMPTY',
  ONLY_ONE_APPROVER_SETTING_CAN_BE_CONFIGURED_FOR_SELF_REQUESTER = 'ONLY_ONE_APPROVER_SETTING_CAN_BE_CONFIGURED_FOR_SELF_REQUESTER',
  ONLY_ONE_APPROVER_SETTING_CAN_BE_CONFIGURED_FOR_FORM_CONTACT = 'ONLY_ONE_APPROVER_SETTING_CAN_BE_CONFIGURED_FOR_FORM_CONTACT',
  SELECT_ORGANIZATION_USER_WORKSPACE_FOR_THE_CONDITION_REQUEST = 'SELECT_ORGANIZATION_USER_WORKSPACE_FOR_THE_CONDITION_REQUEST',
  SELECT_LEAVE_TYPE_FOR_THE_CONDITION_LEAVE_TYPE = 'SELECT_LEAVE_TYPE_FOR_THE_CONDITION_LEAVE_TYPE',
  ADD_VALUE_THE_CONDITION_LEAVE_DURATION = 'ADD_VALUE_THE_CONDITION_LEAVE_DURATION',
  APPROVAL_APPLIED_LEAVE_TYPE_EXISTED = 'APPROVAL_APPLIED_LEAVE_TYPE_EXISTED',
  APPROVAL_FLOW_INVALID = 'APPROVAL_FLOW_INVALID',
  CONDITION_GROUP_LIST_CAN_NOT_EMPTY = 'CONDITION_GROUP_LIST_CAN_NOT_EMPTY',

  APPROVAL_GROUP_ID_CAN_NOT_EMPTY = 'APPROVAL_GROUP_ID_CAN_NOT_EMPTY',
  APPROVAL_ADMINISTRATOR_CAN_NOT_EMPTY = 'APPROVAL_ADMINISTRATOR_CAN_NOT_EMPTY',
  CAN_DELETE_APPROVAL_GROUP_SETTING = 'CAN_DELETE_APPROVAL_GROUP_SETTING',
  APPROVAL_NODE_INFO_CAN_NOT_EMPTY = 'APPROVAL_NODE_INFO_CAN_NOT_EMPTY',

  /**
   * * Day Off
   */
  DAY_OFF_NOT_FOUND = 'DAY_OFF_NOT_FOUND',
  DAY_OFF_EXISTED_IN_GROUP = 'DAY_OFF_EXISTED_IN_GROUP',
  CAN_NOT_DELETE_DAY_OFF_PASSED = 'CAN_NOT_DELETE_DAY_OFF_PASSED',
  HOLIDAY_ALREADY_EXISTED = 'HOLIDAY_ALREADY_EXISTED',
  LOOP_CONFIG_ERROR = 'LOOP_CONFIG_ERROR',
  FORMAT_YEAR_INVALID = 'FORMAT_YEAR_INVALID',
  CAN_NOT_UPDATE_PASSED_HOLIDAY = 'CAN_NOT_UPDATE_PASSED_HOLIDAY',
  DAY_OFF_DATE_MUST_EQUAL_LARGER_THAN_NOW = 'DAY_OFF_DATE_MUST_EQUAL_LARGER_THAN_NOW',
  DAY_OFF_LESS_THAN_NOW = 'DAY_OFF_LESS_THAN_NOW',
  DAY_OFF_GROUP_NOT_EXISTED = 'DAY_OFF_GROUP_NOT_EXISTED',
  /**
   * * Appliance
   */
  LEAVE_APPLIANCE_NOT_VALID = 'LEAVE_APPLIANCE_NOT_VALID',
  APPLIANCE_NOT_FOUND = 'APPLIANCE_NOT_FOUND',
  APPLIANCE_REVOKE_NOT_FOUND = 'APPLIANCE_REVOKE_NOT_FOUND',
  APPLIANCE_TYPE_NOT_FOUND = 'APPLIANCE_TYPE_NOT_FOUND',
  CAN_NOT_CHANGE_STATUS_OF_APPLIANCE_STEP = 'CAN_NOT_CHANGE_STATUS_OF_APPLIANCE_STEP',
  APPLIANCE_REJECT_REASON_CAN_NOT_EMPTY = 'APPLIANCE_REJECT_REASON_CAN_NOT_EMPTY',
  APPLIANCE_CAN_NOT_REVOKE = 'APPLIANCE_CAN_NOT_REVOKE',
  APPLIANCE_IS_AUTO_REVOKED = 'APPLIANCE_IS_AUTO_REVOKED',
  APPLIANCE_REVOKE_IS_IN_PROCESS = 'APPLIANCE_REVOKE_IS_IN_PROCESS',
  APPLIANCE_NOT_VALID = 'APPLIANCE_NOT_VALID',
  NOT_DELETE_CHANGE_SHIFT_APPLIANCE_PAST = 'NOT_DELETE_CHANGE_SHIFT_APPLIANCE_PAST',
  NOT_CHANGE_STATUS_APPLIANCE_NOT_PENDING = 'NOT_CHANGE_STATUS_APPLIANCE_NOT_PENDING',
  USER_WORKSPACE_APPLIANCE_NOT_FOUND = 'USER_WORKSPACE_APPLIANCE_NOT_FOUND',
  CANNOT_REMOVE_CHANGE_SHIFT_APPLIANCE = 'CANNOT_REMOVE_CHANGE_SHIFT_APPLIANCE',
  REACH_LIMIT_CLAIM_APPLIANCE_PER_MONTH = 'REACH_LIMIT_CLAIM_APPLIANCE_PER_MONTH',
  ONLY_CAN_SUBMIT_CLAIM_APPLIANCE_WITHIN_DAY = 'ONLY_CAN_SUBMIT_CLAIM_APPLIANCE_WITHIN_DAY',
  ONLY_CAN_SUBMIT_REQUEST_BEFORE_APPLIED_APPLIANCE_DAY = 'ONLY_CAN_SUBMIT_REQUEST_BEFORE_APPLIED_APPLIANCE_DAY',
  ONLY_CAN_SUBMIT_CLAIM_APPLIANCE_FOR_PAST_DAY = 'ONLY_CAN_SUBMIT_CLAIM_APPLIANCE_FOR_PAST_DAY',
  CLAIM_APPLIANCE_INVALID = 'CLAIM_APPLIANCE_INVALID',
  CHANGE_SHIFT_APPLIANCES_NOT_FOUND = 'CHANGE_SHIFT_APPLIANCES_NOT_FOUND',
  ROTATE_SHIFT_APPLIANCES_NOT_FOUND = 'ROTATE_SHIFT_APPLIANCES_NOT_FOUND',
  REGISTER_SHIFT_APPLIANCES_NOT_FOUND = 'REGISTER_SHIFT_APPLIANCES_NOT_FOUND',
  CLAIM_WORKING_DAY_APPLIANCES_NOT_FOUND = 'CLAIM_WORKING_DAY_APPLIANCES_NOT_FOUND',
  CANNOT_REMOVE_CLAIM_WORKING_DAY_APPLIANCE_IN_THE_PAST = 'CANNOT_REMOVE_CLAIM_WORKING_DAY_APPLIANCE_IN_THE_PAST',
  NOT_ALLOW_REGISTER_SHIFT = 'NOT_ALLOW_REGISTER_SHIFT',
  CAN_NOT_REVOKE_REJECTED_REVOKE_APPLIANCE = 'CAN_NOT_REVOKE_REJECTED_REVOKE_APPLIANCE',
  CANNOT_CHANGE_APPLIANCE_IN_REVOKE_PROCESS = 'CANNOT_CHANGE_APPLIANCE_IN_REVOKE_PROCESS',
  CLAIM_APPLIANCE_DATE_INVALID = 'CLAIM_APPLIANCE_DATE_INVALID',
  CLAIM_APPLIANCE_EXISTED = 'CLAIM_APPLIANCE_EXISTED',
  NOT_SUPPORT_METHOD_CHECKIN_APPLIANCE = 'NOT_SUPPORT_METHOD_CHECKIN_APPLIANCE',
  ADMIN_APPROVED_APPLIANCE = 'ADMIN_APPROVED_APPLIANCE',
  ADMIN_REJECTED_APPLIANCE = 'ADMIN_REJECTED_APPLIANCE',
  CANNOT_CLAIM_FULL_WORKING_DAY = 'CANNOT_CLAIM_FULL_WORKING_DAY',
  CANNOT_CLAIM_UNFINISHED_DAY = 'CANNOT_CLAIM_UNFINISHED_DAY',
  CANNOT_CLAIM_IN_DAY_WITHOUT_SHIFT = 'CANNOT_CLAIM_IN_DAY_WITHOUT_SHIFT',
  CANNOT_CLAIM_IN_DAY_FUTURE = 'CANNOT_CLAIM_IN_DAY_FUTURE',
  CANNOT_CLAIM_WORKING_DAY = 'CANNOT_CLAIM_WORKING_DAY',

  /**
   * * DAY_OFF_GROUP
   */
  DAY_OFF_GROUP_NOT_FOUND = 'DAY_OFF_GROUP_NOT_FOUND',
  CAN_NOT_DELETE_DAY_OFF_GROUP_EXISTED = 'CAN_NOT_DELETE_DAY_OFF_GROUP_EXISTED',
  DAY_OFF_GROUP_EXISTED = 'DAY_OFF_GROUP_EXISTED',

  /**
   * *  Shift
   */
  SHIFT_NOT_FOUND = 'SHIFT_NOT_FOUND',
  FROM_TIME_MUST_EQUAL_LESS_THAN_TO_TIME = 'FROM_TIME_MUST_EQUAL_LESS_THAN_TO_TIME',
  TIME_SHIFT_BREAK_MUST_BE_WITHIN_THE_TIME_SHIFT = 'TIME_SHIFT_BREAK_MUST_BE_WITHIN_THE_TIME_SHIFT',
  CANNOT_REMOVE_SHIFT_INITIAL_DEFAULT = 'CANNOT_REMOVE_SHIFT_INITIAL_DEFAULT',
  SHIFT_CODE_IS_EXIST = 'SHIFT_CODE_IS_EXIST',
  SHIFT_TIME_COMPENSATIONS_NOT_VALID = 'SHIFT_TIME_COMPENSATIONS_NOT_VALID',
  TIME_SHIFT_HOUR_DUPLICATE = 'TIME_SHIFT_HOUR_DUPLICATE',
  ALLOW_CHECKIN_LATE_MINUTES_MUST_LESS_THAN_NOT_CHECKIN_AFTER_MINUTES = 'ALLOW_CHECKIN_LATE_MINUTES_MUST_LESS_THAN_NOT_CHECKIN_AFTER_MINUTES',
  ALLOW_CHECKIN_EARLY_TIME_MUST_LESS_THAN_FROM_TIME = 'ALLOW_CHECKIN_EARLY_TIME_MUST_LESS_THAN_FROM_TIME',
  ALLOW_CHECKOUT_EARLY_MINUTES_MUST_LESS_THAN_NOT_CHECKOUT_BEFORE_MINUTES = 'ALLOW_CHECKOUT_EARLY_MINUTES_MUST_LESS_THAN_NOT_CHECKOUT_BEFORE_MINUTES',
  ALLOW_CHECKOUT_LATE_TIME_MUST_GREATER_THAN_TO_TIME = 'ALLOW_CHECKOUT_LATE_TIME_MUST_GREATER_THAN_TO_TIME',
  TIME_NEXT_SHIFT_HOUR_MUST_GREATER_THAN_PREV_SHIFT_HOUR = 'TIME_NEXT_SHIFT_HOUR_MUST_GREATER_THAN_PREV_SHIFT_HOUR',
  SHIFT_HOUR_INVALID = 'SHIFT_HOUR_INVALID',
  SHIFT_BREAK_INVALID = 'SHIFT_BREAK_INVALID',
  TOTAL_SHIFT_HOURS_IS_WRONG = 'TOTAL_SHIFT_HOURS_IS_WRONG',
  TIME_SHIFT_HOUR_NOT_VALID = 'TIME_SHIFT_HOUR_NOT_VALID',
  CONFIG_TIME_SHIFT_HOUR_NOT_VALID = 'CONFIG_TIME_SHIFT_HOUR_NOT_VALID',
  APPLY_DATE_MUST_EQUAL_LARGER_THAN_NOW = 'APPLY_DATE_MUST_EQUAL_LARGER_THAN_NOW',
  SHIFT_APPLY_DATE_INVALID = 'SHIFT_APPLY_DATE_INVALID',
  SHIFT_GROUP_NOT_FOUND = 'SHIFT_GROUP_NOT_FOUND',
  SHIFT_GROUP_CODE_EXISTED = 'SHIFT_GROUP_CODE_EXISTED',
  DAY_OFF_GROUP_CAN_NOT_EMPTY = 'DAY_OFF_GROUP_CAN_NOT_EMPTY',
  SHIFT_CAN_NOT_EMPTY = 'SHIFT_CAN_NOT_EMPTY',
  SHIFT_GROUP_DUPLICATE = 'SHIFT_GROUP_DUPLICATE',
  SHIFT_GROUP_SCHEDULE_NOT_FOUND = 'SHIFT_GROUP_SCHEDULE_NOT_FOUND',
  SHIFT_GROUP_SCHEDULE_SHIFT_INVALID = 'SHIFT_GROUP_SCHEDULE_SHIFT_INVALID',
  SHIFT_GROUP_USER_WORKSPACE_OUT_OF_SCOPE = 'SHIFT_GROUP_USER_WORKSPACE_OUT_OF_SCOPE',
  RANGE_TIME_SHIFT_HOUR_MUST_LESS_THAN_24_HOUR = 'RANGE_TIME_SHIFT_HOUR_MUST_LESS_THAN_24_HOUR',
  SHIFT_HOUR_APPLIED_SHIFT_GROUP_DUPLICATE = 'SHIFT_HOUR_APPLIED_SHIFT_GROUP_DUPLICATE',
  CANNOT_REMOVE_SHIFT_EXISTING_IN_SHIFT_GROUP = 'CANNOT_REMOVE_SHIFT_EXISTING_IN_SHIFT_GROUP',
  SHIFT_EXISTING_IN_SHIFT_GROUP_SPECIAL_DATE = 'SHIFT_EXISTING_IN_SHIFT_GROUP_SPECIAL_DATE',
  SHIFT_APPLIED_SHIFT_SCHEDULE_DUPLICATE = 'SHIFT_APPLIED_SHIFT_SCHEDULE_DUPLICATE',
  CANNOT_REMOVE_DAY_OF_GROUP_EXISTING_IN_SHIFT_GROUP = 'CANNOT_REMOVE_DAY_OF_GROUP_EXISTING_IN_SHIFT_GROUP',
  DAY_OF_EXISTING_IN_SHIFT_GROUP = 'DAY_OF_EXISTING_IN_SHIFT_GROUP',
  CANNOT_UPDATE_SHIFT_GROUP_SCHEDULE_IN_THE_PAST = 'CANNOT_UPDATE_SHIFT_GROUP_SCHEDULE_IN_THE_PAST',
  CREATE_SHIFT_GROUP_SUCCESS_BUT_CREATE_SCHEDULE_FAIL = 'CREATE_SHIFT_GROUP_SUCCESS_BUT_CREATE_SCHEDULE_FAIL',
  SHIFT_APPLY_DUPLICATE_IN_CURRENT_DATE = 'SHIFT_APPLY_DUPLICATE_IN_CURRENT_DATE',
  SHIFT_APPLY_DUPLICATE_IN_OTHER_DATE = 'SHIFT_APPLY_DUPLICATE_IN_OTHER_DATE',

  /**
   * * Shift group
   */
  CANNOT_REMOVE_SHIFT_GROUP_INITIAL_DEFAULT = 'CANNOT_REMOVE_SHIFT_GROUP_INITIAL_DEFAULT',
  STAFF_IN_SHIFT_GROUP_EXISTED = 'STAFF_IN_SHIFT_GROUP_EXISTED',
  SHIFT_GROUP_FLEXIBLE_NOT_FOUND = 'SHIFT_GROUP_FLEXIBLE_NOT_FOUND',
  SHIFT_FLEXIBLE_NOT_EMPTY = 'SHIFT_FLEXIBLE_NOT_EMPTY',
  DAY_OF_WEEK_CANNOT_BE_DUPLICATED = 'DAY_OF_WEEK_CANNOT_BE_DUPLICATED',
  SHIFT_GROUP_FIXED_NOT_FOUND = 'SHIFT_GROUP_FIXED_NOT_FOUND',
  WORKING_HOUR_NOT_EMPTY = 'WORKING_HOUR_NOT_EMPTY',
  UNABLE_TO_SELECT_A_SHIFT_WITH_THE_SAME_TIME_AS_THE_SHIFT_OF_ANOTHER_DAY = 'UNABLE_TO_SELECT_A_SHIFT_WITH_THE_SAME_TIME_AS_THE_SHIFT_OF_ANOTHER_DAY',
  WORKING_HOUR_INVALID = 'WORKING_HOUR_INVALID',
  WORKING_HOUR_MUST_LESS_THAN_24_HOUR = 'WORKING_HOUR_MUST_LESS_THAN_24_HOUR',
  CAN_NOT_EXPORT_SCHEDULE_ON_THE_PASS = 'CAN_NOT_EXPORT_SCHEDULE_ON_THE_PASS',
  SOURCE_SHIFT_CAN_NOT_EQUAL_DESTINATION_SHIFT = 'SOURCE_SHIFT_CAN_NOT_EQUAL_DESTINATION_SHIFT',
  USER_WORKSPACE_ALREADY_HAS_THIS_SHIFT_IN_DATE = 'USER_WORKSPACE_ALREADY_HAS_THIS_SHIFT_IN_DATE',
  MUST_CHOOSE_SOURCE_SHIFT_TO_CHANGE_SHIFT = 'MUST_CHOOSE_SOURCE_SHIFT_TO_CHANGE_SHIFT',
  MUST_CHOOSE_DESTINATION_SHIFT_TO_CHANGE_SHIFT = 'MUST_CHOOSE_DESTINATION_SHIFT_TO_CHANGE_SHIFT',
  CANNOT_SHIFT_WITH_HOUR_INVALID = 'CANNOT_SHIFT_WITH_HOUR_INVALID',
  USER_WORKSPACE_DONT_HAVE_SHIFT_IN_DATE = 'USER_WORKSPACE_DONT_HAVE_SHIFT_IN_DATE',
  SHIFT_APPLY_DUPLICATE_WITH_USER_WORKSPACE_SHIFT = 'SHIFT_APPLY_DUPLICATE_WITH_USER_WORKSPACE_SHIFT',
  USER_WORKSPACE_ALREADY_HAS_SHIFT_IN_DATE = 'USER_WORKSPACE_ALREADY_HAS_SHIFT_IN_DATE',

  /**
   * Rotate shift appliance
   */
  CANNOT_ROTATE_SHIFT_APPLIANCE_ON_THE_PAST = 'CANNOT_ROTATE_SHIFT_APPLIANCE_ON_THE_PAST',
  USER_WORKSPACE_NOT_IN_SHIFT_GROUP_SCHEDULE_OR_SHIFT_GROUP_SCHEDULE_DATE = 'USER_WORKSPACE_NOT_IN_SHIFT_GROUP_SCHEDULE_OR_SHIFT_GROUP_SCHEDULE_DATE',
  INVALID_REQUEST_APPLIANCE_TIME = 'INVALID_REQUEST_APPLIANCE_TIME',
  SOURCE_ROTATE_SHIFT_CAN_NOT_EQUAL_DESTINATION_ROTATE_SHIFT = 'SOURCE_ROTATE_SHIFT_CAN_NOT_EQUAL_DESTINATION_ROTATE_SHIFT',
  ROTATE_SHIFT_APPLIANCE_NOT_FOUND = 'ROTATE_SHIFT_APPLIANCE_NOT_FOUND',
  CANNOT_REMOVE_ROTATE_SHIFT_APPLIANCE = 'CANNOT_REMOVE_ROTATE_SHIFT_APPLIANCE',

  /**
   * Shift group special date
   */
  SHIFT_GROUP_SPECIAL_DATE_NOT_FOUND = 'SHIFT_GROUP_SPECIAL_DATE_NOT_FOUND',
  SHIFT_GROUP_SPECIAL_DATE_EXISTED = 'SHIFT_GROUP_SPECIAL_DATE_EXISTED',
  SELECT_A_SHIFT_FOR_THE_SHIFT_GROUP_SPECIAL_DATE = 'SELECT_A_SHIFT_FOR_THE_SHIFT_GROUP_SPECIAL_DATE',
  SHIFT_GROUP_SPECIAL_DATE_NOT_VALID = 'SHIFT_GROUP_SPECIAL_DATE_NOT_VALID',

  /**
   * * Checkin method
   */
  MACHINE_IS_EXISTED = 'MACHINE_IS_EXISTED',
  MACHINE_NOT_FOUND = 'MACHINE_NOT_FOUND',
  OFFICE_WIFI_CAN_NOT_EMPTY = 'OFFICE_WIFI_CAN_NOT_EMPTY',
  OFFICE_LOCATION_CAN_NOT_EMPTY = 'OFFICE_LOCATION_CAN_NOT_EMPTY',
  OFFICE_MACHINE_CAN_NOT_EMPTY = 'OFFICE_MACHINE_CAN_NOT_EMPTY',
  WIFI_NOT_NOT_FOUND = 'WIFI_NOT_NOT_FOUND',
  LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND',
  QRCODE_LOGIN_MACHINE_INVALID = 'QRCODE_LOGIN_MACHINE_INVALID',
  MACHINE_BELONG_TO_ANOTHER_OFFICE = 'MACHINE_BELONG_TO_ANOTHER_OFFICE',
  MACHINE_NOT_FOUND_IN_OFFICE = 'MACHINE_NOT_FOUND_IN_OFFICE',
  QRCODE_CHECKIN_MACHINE_INVALID = 'QRCODE_CHECKIN_MACHINE_INVALID',
  MACHINE_HASH_INVALID = 'MACHINE_HASH_INVALID',
  CHECKIN_INVALID = 'CHECKIN_INVALID',
  CANNOT_LOGIN_MACHINE = 'CANNOT_LOGIN_MACHINE',
  CHECKIN_LOCATION_INVALID = 'CHECKIN_LOCATION_INVALID',
  CHECKIN_WIFI_INVALID = 'CHECKIN_WIFI_INVALID',
  REACH_LIMIT_TRIAL_MACHINE = 'REACH_LIMIT_TRIAL_MACHINE',
  QRCODE_LOGIN_CMS_INVALID = 'QRCODE_LOGIN_CMS_INVALID',
  QRCODE_LOGIN_CMS_EXPIRED = 'QRCODE_LOGIN_CMS_EXPIRED',

  /**
   * * Overtime
   */
  OVERTIME_IS_EXISTED = 'OVERTIME_IS_EXISTED',
  OVERTIME_NOT_FOUND = 'OVERTIME_NOT_FOUND',
  OVERTIME_SCOPES_INVALID = 'OVERTIME_SCOPES_INVALID',
  OVERTIME_RULE_INVALID = 'OVERTIME_RULE_INVALID',
  CANNOT_REMOVE_OVERTIME_INITIAL_DEFAULT = 'CANNOT_REMOVE_OVERTIME_INITIAL_DEFAULT',
  OVERTIME_APPLIANCE_NOT_FOUND = 'OVERTIME_APPLIANCE_NOT_FOUND',
  CANNOT_REMOVE_OVERTIME_APPLIANCE = 'CANNOT_REMOVE_OVERTIME_APPLIANCE',
  ONLY_CHANGE_STATUS_APPROVED_OR_REJECTED = 'ONLY_CHANGE_STATUS_APPROVED_OR_REJECTED',
  ADMIN_CANNOT_CHANGE_PERMISSION_APPLIANCE_STATUS = 'ADMIN_CANNOT_CHANGE_PERMISSION_APPLIANCE_STATUS',
  CANNOT_SEND_OVERTIME_APPLIANCE_BEFORE_SHIFT_END = 'CANNOT_SEND_OVERTIME_APPLIANCE_BEFORE_SHIFT_END',
  OVERTIME_APPLIANCE_IS_EXISTED = 'OVERTIME_APPLIANCE_IS_EXISTED',
  OVERTIME_APPLIANCE_LIMITED = 'OVERTIME_APPLIANCE_LIMITED',
  OVERTIME_NOT_ALLOW_WORKING_DAY = 'OVERTIME_NOT_ALLOW_WORKING_DAY',
  OVERTIME_NOT_ALLOW_DAY_OFF = 'OVERTIME_NOT_ALLOW_DAY_OFF',
  OVERTIME_NOT_ALLOW_HOLIDAY = 'OVERTIME_NOT_ALLOW_HOLIDAY',
  OVERTIME_MIN_REACH_INVALID = 'OVERTIME_MIN_REACH_INVALID',
  CANNOT_SEND_OVERTIME_APPLIANCE_METHOD_AUTO = 'CANNOT_SEND_OVERTIME_APPLIANCE_METHOD_AUTO',
  ALLOW_OVERTIME_AFTER_SHIFT_END_INVALID = 'ALLOW_OVERTIME_AFTER_SHIFT_END_INVALID',
  OVERTIME_CONVERT_TYPE_IS_REQUIRED = 'OVERTIME_CONVERT_TYPE_IS_REQUIRED',
  NIGHT_SHIFT_OVERTIME_CONVERT_TYPE_IS_REQUIRED = 'NIGHT_SHIFT_OVERTIME_CONVERT_TYPE_IS_REQUIRED',
  OVERTIME_MUST_LESS_THAN_24_HOUR = 'OVERTIME_MUST_LESS_THAN_24_HOUR',

  /**
   * * In/out rules
   */
  CANNOT_CHECKIN_EARLY = 'CANNOT_CHECKIN_EARLY',
  CANNOT_CHECKIN_LATE = 'CANNOT_CHECKIN_LATE',
  CANNOT_CHECKOUT_EARLY = 'CANNOT_CHECKOUT_EARLY',
  CANNOT_CHECKOUT_LATE = 'CANNOT_CHECKOUT_LATE',
  CANNOT_CHECKIN = 'CANNOT_CHECKIN',

  /**
   * * Shift schedule appliance
   */
  SHIFT_SCHEDULE_APPLIANCE_NOT_FOUND = 'SHIFT_SCHEDULE_APPLIANCE_NOT_FOUND',
  CANNOT_REMOVE_SHIFT_SCHEDULE_APPLIANCE = 'CANNOT_REMOVE_SHIFT_SCHEDULE_APPLIANCE',

  /**
   * * Remote working
   */
  REMOTE_WORKING_APPLIANCE_NOT_FOUND = 'REMOTE_WORKING_APPLIANCE_NOT_FOUND',
  CANNOT_DELETE_REMOTE_WORKING_APPLIANCE_IN_THE_PAST = 'CANNOT_DELETE_REMOTE_WORKING_APPLIANCE_IN_THE_PAST',
  TOTAL_MINUTES_REMOTE_WORKING_APPLIANCE_INVALID = 'TOTAL_MINUTES_REMOTE_WORKING_APPLIANCE_INVALID',
  CANNOT_SEND_REMOTE_WORKING_APPLIANCE_IN_DAY_WITHOUT_SHIFT = 'CANNOT_SEND_REMOTE_WORKING_APPLIANCE_IN_DAY_WITHOUT_SHIFT',
  CANNOT_SEND_REMOTE_WORKING_APPLIANCE_DUPLICATE_LEAVE_APPLIANCE = 'CANNOT_SEND_REMOTE_WORKING_APPLIANCE_DUPLICATE_LEAVE_APPLIANCE',
  CHECKIN_IMAGE_REQUEST = 'CHECKIN_IMAGE_REQUEST',
  CHECKIN_LOCATION_REQUEST = 'CHECKIN_LOCATION_REQUEST',
  CHECKIN_DATE_INVALID = 'CHECKIN_DATE_INVALID',
  NOT_FOUND_SHIFT_INVALID_REMOTE_WORKING = 'NOT_FOUND_SHIFT_INVALID_REMOTE_WORKING',
  REMOTE_WORKING_APPLIANCE_REQUIRE_IMAGE = 'REMOTE_WORKING_APPLIANCE_REQUIRE_IMAGE',
  REMOTE_WORKING_APPLIANCE_REQUIRE_LOCATION = 'REMOTE_WORKING_APPLIANCE_REQUIRE_LOCATION',

  /**
   * * Shift appliance
   */
  SHIFT_APPLIANCE_DUPLICATE_IN_DATE = 'SHIFT_APPLIANCE_DUPLICATE_IN_DATE',
  DATES_APPLIANCE_INVALID = 'DATES_APPLIANCE_INVALID',
  SHIFT_APPLIANCE_EXISTED = 'SHIFT_APPLIANCE_EXISTED',
  ROTATE_SHIFT_APPLIANCE_DUPLICATE_IN_DATE = 'ROTATE_SHIFT_APPLIANCE_DUPLICATE_IN_DATE',
  CHANGE_SHIFT_APPLIANCE_DUPLICATE_IN_DATE = 'CHANGE_SHIFT_APPLIANCE_DUPLICATE_IN_DATE',
  SHIFT_SCHEDULE_APPLIANCE_DUPLICATE_IN_DATE = 'SHIFT_SCHEDULE_APPLIANCE_DUPLICATE_IN_DATE',
  CAN_NOT_REQUEST_APPLIANCE_USER_WORKSPACE_NOT_IN_SHIFT_GROUP_SCHEDULE = 'CAN_NOT_REQUEST_APPLIANCE_USER_WORKSPACE_NOT_IN_SHIFT_GROUP_SCHEDULE',
  SHIFT_APPLIANCE_DUPLICATE_AUTO_REJECT = 'SHIFT_APPLIANCE_DUPLICATE_AUTO_REJECT',

  OFFICE_NOT_FOUND = 'OFFICE_NOT_FOUND',
  OFFICE_IS_EXISTED = 'OFFICE_IS_EXISTED',
  OFFICE_IS_IN_SHIFT_GROUP = 'OFFICE_IS_IN_SHIFT_GROUP',
  NO_OFFICE_LOCATION = 'NO_OFFICE_LOCATION',
  NO_OFFICE_WIFI = 'NO_OFFICE_WIFI',
  NO_OFFICE_MACHINE = 'NO_OFFICE_MACHINE',
  OFFICE_FLOOR_NOT_FOUND = 'OFFICE_FLOOR_NOT_FOUND',
  OFFICE_QRCODE_INVALID = 'OFFICE_QRCODE_INVALID',

  SALARY_PERIOD_NOT_FOUND = 'SALARY_PERIOD_NOT_FOUND',
  SALARY_PERIOD_IS_EXISTED = 'SALARY_PERIOD_IS_EXISTED',
  SALARY_PERIOD_LOOP_FROM_DATE_INVALID = 'SALARY_PERIOD_LOOP_FROM_DATE_INVALID',
  SALARY_PERIOD_DATE_INVALID = 'SALARY_PERIOD_DATE_INVALID',
  CAN_NOT_UPDATE_SALARY_PERIOD_IN_PAST = 'CAN_NOT_UPDATE_SALARY_PERIOD_IN_PAST',
  CAN_NOT_REMOVE_SALARY_PERIOD_IN_PAST = 'CAN_NOT_REMOVE_SALARY_PERIOD_IN_PAST',
  SALARY_GRADE_IS_EXISTED = 'SALARY_GRADE_IS_EXISTED',
  SALARY_GRADE_NOT_FOUND = 'SALARY_GRADE_NOT_FOUND',
  SALARY_RANK_IS_EXISTED = 'SALARY_RANK_IS_EXISTED',
  SALARY_RANK_NOT_FOUND = 'SALARY_RANK_NOT_FOUND',
  SALARY_PARAMETER_NOT_FOUND = 'SALARY_PARAMETER_NOT_FOUND',
  SALARY_PARAMETER_CODE_EXISTED = 'SALARY_PARAMETER_CODE_EXISTED',
  CAN_NOT_DELETE_OR_INACTIVE_SALARY_GRADE = 'CAN_NOT_DELETE_OR_INACTIVE_SALARY_GRADE',
  CAN_NOT_INACTIVE_SALARY_GRADE = 'CAN_NOT_INACTIVE_SALARY_GRADE',
  SALARY_RANK_IS_IN_USER_WORKSPACE_LABOR_CONTRACT = 'SALARY_RANK_IS_IN_USER_WORKSPACE_LABOR_CONTRACT',
  SALARY_RANK_IS_IN_SALARY_INFORMATION = 'SALARY_RANK_IS_IN_SALARY_INFORMATION',
  CANNOT_UPDATE_SALARY_RANK_COEFFICIENT = 'CANNOT_UPDATE_SALARY_RANK_COEFFICIENT',
  CANNOT_UPDATE_SALARY_RANK_STATUS = 'CANNOT_UPDATE_SALARY_RANK_STATUS',
  CANNOT_CHANGE_SALARY_METHOD_CONFIG_OF_IN_THE_PAST = 'CANNOT_CHANGE_SALARY_METHOD_CONFIG_OF_IN_THE_PAST',

  REMOVE_SALARY_PARAMETER_EXISTED_MINIMUM_AMOUNT = 'REMOVE_SALARY_PARAMETER_EXISTED_MINIMUM_AMOUNT',
  CHANGE_ACTIVE_TO_INACTIVE_SALARY_PARAMETER = 'CHANGE_ACTIVE_TO_INACTIVE_SALARY_PARAMETER',
  CHANGE_INACTIVE_TO_ACTIVE_SALARY_PARAMETER = 'CHANGE_INACTIVE_TO_ACTIVE_SALARY_PARAMETER',
  CAN_NOT_REMOVE_SALARY_PARAMETER_EXISTED_MINIMUM_AMOUNT = 'CAN_NOT_REMOVE_SALARY_PARAMETER_EXISTED_MINIMUM_AMOUNT',
  MINIMUM_AMOUNT_NOT_FOUND = 'MINIMUM_AMOUNT_NOT_FOUND',
  MINIMUM_AMOUNT_CODE_EXISTED = 'MINIMUM_AMOUNT_CODE_EXISTED',
  CAN_NOT_DELETE_SALARY_RANK = 'CAN_NOT_DELETE_SALARY_RANK',
  CAN_NOT_CHANGE_STATUS_SALARY_RANK = 'CAN_NOT_CHANGE_STATUS_SALARY_RANK',
  MINIMUM_AMOUNT_SCOPES_INVALID = 'MINIMUM_AMOUNT_SCOPES_INVALID',
  MINIMUM_NORM_INVALID_DATE = 'MINIMUM_NORM_INVALID_DATE',
  MINIMUM_NORM_NOT_FOUND = 'MINIMUM_NORM_NOT_FOUND',
  NORM_TYPE_NOT_VALID = 'NORM_TYPE_NOT_VALID',
  CANNOT_EDIT_NORM_TYPE = 'CANNOT_EDIT_NORM_TYPE',
  CANNOT_EDIT_MINIMUM_NORM_IN_THE_PAST = 'CANNOT_EDIT_MINIMUM_NORM_IN_THE_PAST',
  CANNOT_EDIT_MINIMUM_NORM_VALUE_IN_THE_PAST = 'CANNOT_EDIT_MINIMUM_NORM_VALUE_IN_THE_PAST',
  MINIMUM_AMOUNT_SCOPE_TYPE_ALL_EXISTED = 'MINIMUM_AMOUNT_SCOPE_TYPE_ALL_EXISTED',
  MINIMUM_AMOUNT_SCOPE_TYPE_NONE_NOT_VALID = 'MINIMUM_AMOUNT_SCOPE_TYPE_NONE_NOT_VALID',
  SALARY_METHOD_CONFIG_NOT_FOUND = 'SALARY_METHOD_CONFIG_NOT_FOUND',
  CANNOT_REMOVE_APPLIED_SALARY_METHOD_CONFIG = 'CANNOT_REMOVE_APPLIED_SALARY_METHOD_CONFIG',
  SALARY_METHOD_CONFIG_INVALID_DATE = 'SALARY_METHOD_CONFIG_INVALID_DATE',
  SALARY_PAY_METHOD_NOT_EMPTY = 'SALARY_PAY_METHOD_NOT_EMPTY',
  SALARY_PAY_METHOD_PERCENT_MUST_EQUAL_100 = 'SALARY_PAY_METHOD_PERCENT_MUST_EQUAL_100',
  SALARY_GRADE_NOT_EMPTY = 'SALARY_GRADE_NOT_EMPTY',
  SALARY_RANK_NOT_EMPTY = 'SALARY_RANK_NOT_EMPTY',
  CANNOT_UPDATE_SALARY_METHOD_CONFIG_APPLIED_IN_THE_PAST = 'CANNOT_UPDATE_SALARY_METHOD_CONFIG_APPLIED_IN_THE_PAST',
  CANNOT_UPDATE_VALID_DATE_OF_SALARY_METHOD_CONFIG_APPLIED_IN_THE_PAST = 'CANNOT_UPDATE_VALID_DATE_OF_SALARY_METHOD_CONFIG_APPLIED_IN_THE_PAST',
  VALID_DATE_MUST_LARGER_THAN_CURRENT_DATE_AND_LESS_THAN_EXPIRES_DATE = 'VALID_DATE_MUST_LARGER_THAN_CURRENT_DATE_AND_LESS_THAN_EXPIRES_DATE',
  ONLY_ALLOW_CHANGE_EXPIRES_DATE_FOR_SALARY_METHOD_CONFIG_IN_THE_PAST = 'ONLY_ALLOW_CHANGE_EXPIRES_DATE_FOR_SALARY_METHOD_CONFIG_IN_THE_PAST',
  SALARY_PAY_METHOD_DUPLICATED = 'SALARY_PAY_METHOD_DUPLICATED',
  VALID_DATE_MUST_BE_IN_CURRENT_SALARY_PERIOD = 'VALID_DATE_MUST_BE_IN_CURRENT_SALARY_PERIOD',

  SALARY_INFORMATION_NOT_FOUND = 'SALARY_INFORMATION_NOT_FOUND',
  CANNOT_UPDATE_SALARY_INFORMATION_EXPIRE = 'CANNOT_UPDATE_SALARY_INFORMATION_EXPIRE',
  ONLY_UPDATE_SALARY_INFORMATION_STATUS = 'ONLY_UPDATE_SALARY_INFORMATION_STATUS',
  CANNOT_UPDATE_SALARY_INFORMATION_IN_PAST = 'CANNOT_UPDATE_SALARY_INFORMATION_IN_PAST',
  CANNOT_UPDATE_SALARY_INFORMATION = 'CANNOT_UPDATE_SALARY_INFORMATION',
  CANNOT_REMOVE_SALARY_INFORMATION = 'CANNOT_REMOVE_SALARY_INFORMATION',
  INVALID_SALARY_INFORMATION_START_DATE = 'INVALID_SALARY_INFORMATION_START_DATE',

  /**
   * * Meetings
   */
  OFFICE_MEETING_ROOM_NOT_FOUND = 'OFFICE_MEETING_ROOM_NOT_FOUND',
  REACH_LIMIT_DAY_BOOKING_IN_ADVANCE = 'REACH_LIMIT_DAY_BOOKING_IN_ADVANCE',
  BOOKING_TIME_NOT_VALID = 'BOOKING_TIME_NOT_VALID',
  REACH_LIMIT_BOOKING_TIME = 'REACH_LIMIT_BOOKING_TIME',
  OFFICE_MEETING_ROOM_PERMISSION_DENIED = 'OFFICE_MEETING_ROOM_PERMISSION_DENIED',
  REPEAT_END_DATE_IS_NOT_EMPTY = 'REPEAT_END_DATE_IS_NOT_EMPTY',
  REPEAT_DATE_IS_NOT_VALID = 'REPEAT_DATE_IS_NOT_VALID',
  CANNOT_CREATE_MEETING_IN_THE_PAST = 'CANNOT_CREATE_MEETING_IN_THE_PAST',
  CUSTOM_REPEAT_INVALID = 'CUSTOM_REPEAT_INVALID',
  CUSTOM_MESSAGE_DUPLICATE_MEETING_ROOM = 'CUSTOM_MESSAGE_DUPLICATE_MEETING_ROOM',
  MEETING_NOT_FOUND = 'MEETING_NOT_FOUND',
  CANNOT_DELETE_MEETING_IN_THE_PAST = 'CANNOT_DELETE_MEETING_IN_THE_PAST',
  ONLY_HOST_CAN_DELETE_MEETING = 'ONLY_HOST_CAN_DELETE_MEETING',
  MEMBER_MEETING_NOT_FOUND = 'MEMBER_MEETING_NOT_FOUND',
  ALREADY_APPROVED_OR_REJECTED_MEETING_REQUEST = 'ALREADY_APPROVED_OR_REJECTED_MEETING_REQUEST',
  CAN_NOT_CHANGE_STATUS_MEETING_REQUEST_IN_THE_PAST = 'CAN_NOT_CHANGE_STATUS_MEETING_REQUEST_IN_THE_PAST',
  REACH_LIMIT_TIME_APPROVED_OR_REJECTED_MEETING_REQUEST = 'REACH_LIMIT_TIME_APPROVED_OR_REJECTED_MEETING_REQUEST',
  CANNOT_CHANGE_MEETING_HOST_STATUS = 'CANNOT_CHANGE_MEETING_HOST_STATUS',
  MEETING_GROUP_NOT_FOUND = 'MEETING_GROUP_NOT_FOUND',
  INVALID_TIME_UPDATE_MEETING_REPORT = 'INVALID_TIME_UPDATE_MEETING_REPORT',
  ONLY_HOST_CAN_UPDATE_MEETING_REPORT = 'ONLY_HOST_CAN_UPDATE_MEETING_REPORT',
  MEETING_REPORT_NOT_FOUND = 'MEETING_REPORT_NOT_FOUND',
  REACH_LIMIT_UPLOAD_MEETING_REPORT_FILE_AND_IMAGE = 'REACH_LIMIT_UPLOAD_MEETING_REPORT_FILE_AND_IMAGE',
  CANNOT_UPDATE_MEETING_IN_THE_PAST = 'CANNOT_UPDATE_MEETING_IN_THE_PAST',
  SCHEDULE_OPTION_CANNOT_EMPTY = 'SCHEDULE_OPTION_CANNOT_EMPTY',
  REPEAT_LAST_WEEK_IN_MONTH_NOT_VALID = 'REPEAT_LAST_WEEK_IN_MONTH_NOT_VALID',
  REPEAT_LAST_DAY_IN_MONTH_NOT_VALID = 'REPEAT_LAST_DAY_IN_MONTH_NOT_VALID',
  INVALID_OFFICE_MEETING_ROOM_VALID_TIME = 'INVALID_OFFICE_MEETING_ROOM_VALID_TIME',
  CANNOT_EXPORT_MEETING_CHECKIN_IN_THE_FUTURE = 'CANNOT_EXPORT_MEETING_CHECKIN_IN_THE_FUTURE',
  CANNOT_EXPORT_MEETING_NOT_REQUIRE_CHECKIN = 'CANNOT_EXPORT_MEETING_NOT_REQUIRE_CHECKIN',
  MEETING_QR_CODE_INVALID = 'MEETING_QR_CODE_INVALID',
  CHECKIN_MEETING_TIME_INVALID = 'CHECKIN_MEETING_TIME_INVALID',
  CHECKOUT_MEETING_TIME_INVALID = 'CHECKOUT_MEETING_TIME_INVALID',
  MEETING_IS_OVER = 'MEETING_IS_OVER',
  CHECKIN_MEETING_SUCCESSFULLY = 'CHECKIN_MEETING_SUCCESSFULLY',
  CANNOT_UPDATE_MEETING_IS_HAPPENING = 'CANNOT_UPDATE_MEETING_IS_HAPPENING',
  CANNOT_UPDATE_MEETING_TO_THE_PAST = 'CANNOT_UPDATE_MEETING_TO_THE_PAST',
  CANNOT_CHANGE_STATUS_OF_MEETING_REQUIRE_ATTENDANCE = 'CANNOT_CHANGE_STATUS_OF_MEETING_REQUIRE_ATTENDANCE',
  CANNOT_UPDATE_DEFAULT_MEETING_GROUP = 'CANNOT_UPDATE_DEFAULT_MEETING_GROUP',
  INVALID_REPEAT_MEETING_END_DATE = 'INVALID_REPEAT_MEETING_END_DATE',
  MEETING_ALREADY_BLOCKED = 'MEETING_ALREADY_BLOCKED',

  /**
   * * Reports
   */
  REPORT_NOT_FOUND = 'REPORT_NOT_FOUND',
  REPORT_IS_EXISTED = 'REPORT_IS_EXISTED',
  REPORT_HISTORY_NOT_FOUND = 'REPORT_HISTORY_NOT_FOUND',
  ONLY_EXPORT_REPORT_TYPE_DEFAULT = 'ONLY_EXPORT_REPORT_TYPE_DEFAULT',
  REPORT_FILE_INVALID = 'REPORT_FILE_INVALID',
  INVALID_EXPORT_ATTRIBUTE = 'INVALID_EXPORT_ATTRIBUTE',
  DUPLICATE_INFORMATION_SIGN_CODE = 'DUPLICATE_INFORMATION_SIGN_CODE',

  UTILITIES_NOT_FOUND = 'UTILITIES_NOT_FOUND',

  START_DATE_CANNOT_BE_IN_THE_PAST = 'START_DATE_CANNOT_BE_IN_THE_PAST',
  REIMBURSEMENT_NOT_FOUND = 'REIMBURSEMENT_NOT_FOUND',
  CANNOT_UPDATE_REIMBURSEMENT_IN_THE_PAST = 'CANNOT_UPDATE_REIMBURSEMENT_IN_THE_PAST',
  CANNOT_DELETE_REIMBURSEMENT_IN_THE_PAST = 'CANNOT_DELETE_REIMBURSEMENT_IN_THE_PAST',

  PAYROLL_POLICY_EXISTED = 'PAYROLL_POLICY_EXISTED',
  PAYROLL_POLICY_NOT_FOUND = 'PAYROLL_POLICY_NOT_FOUND',
  PAYROLL_POLICY_IS_IN_CONTRACT = 'PAYROLL_POLICY_IS_IN_CONTRACT',
  PAYROLL_POLICY_IS_INACTIVE = 'PAYROLL_POLICY_IS_INACTIVE',

  CANNOT_DELETE_SALARY_INFORMATION_IN_THE_PAST = 'CANNOT_DELETE_SALARY_INFORMATION_IN_THE_PAST',
  CANNOT_CREATE_SALARY_INFORMATION_IN_THE_PAST = 'CANNOT_CREATE_SALARY_INFORMATION_IN_THE_PAST',
  INVALID_SALARY_METHOD_CONFIG = 'INVALID_SALARY_METHOD_CONFIG',
  SALARY_CURRENT_IS_REQUIRED = 'SALARY_CURRENT_IS_REQUIRED',

  PAYROLL_ELEMENT_NOT_FOUND = 'PAYROLL_ELEMENT_NOT_FOUND',
  CANNOT_DELETE_PAYROLL_ELEMENT = 'CANNOT_DELETE_PAYROLL_ELEMENT',
  PAYROLL_ELEMENT_EXISTED = 'PAYROLL_ELEMENT_EXISTED',
  CANNOT_UPDATE_PAYROLL_ELEMENT_CODE = 'CANNOT_UPDATE_PAYROLL_ELEMENT_CODE',

  PAYROLL_TABLE_NOT_FOUND = 'PAYROLL_TABLE_NOT_FOUND',
  PAYROLL_TABLE_REQUIRE_USER_WORKSPACE_OR_ORGANIZATION = 'PAYROLL_TABLE_REQUIRE_USER_WORKSPACE_OR_ORGANIZATION',
  CANNOT_UPDATE_PAYROLL_TABLE = 'CANNOT_UPDATE_PAYROLL_TABLE',
  CANNOT_DELETE_PAYROLL_TABLE = 'CANNOT_DELETE_PAYROLL_TABLE',
  SALARY_PERIOD_CANNOT_BE_IN_THE_FUTURE = 'SALARY_PERIOD_CANNOT_BE_IN_THE_FUTURE',
  PAYSLIP_NOT_FOUND = 'PAYSLIP_NOT_FOUND',
  CANNOT_LOCK_PAYROLL_TABLE = 'CANNOT_LOCK_PAYROLL_TABLE',
  CANNOT_SEND_PAYSLIP = 'CANNOT_SEND_PAYSLIP',
  PAYROLL_TABLE_HISTORY_NOT_FOUND = 'PAYROLL_TABLE_HISTORY_NOT_FOUND',
  PERMISSION_LOCK_PAYROLL_TABLE_DENIED = 'PERMISSION_LOCK_PAYROLL_TABLE_DENIED',
  INSUFFICIENT_PERMISSION = 'INSUFFICIENT_PERMISSION',
  USER_WORKSPACE_INVALID_BY_SIGN_COMPANY = 'USER_WORKSPACE_INVALID_BY_SIGN_COMPANY',

  ELEMENT_LIBRARY_EXISTED = 'ELEMENT_LIBRARY_EXISTED',
  REPORT_IS_PENDING = 'REPORT_IS_PENDING',

  /**
   * * Workplace
   */
  WORKPLACE_POST_NOT_FOUND = 'WORKPLACE_POST_NOT_FOUND',
  WORKPLACE_POST_CAN_NOT_EDIT = 'WORKPLACE_POST_CAN_NOT_EDIT',
  WORKPLACE_POST_CAN_NOT_REACTION = 'WORKPLACE_POST_CAN_NOT_REACTION',
  WORKPLACE_POST_CAN_NOT_COMMENT = 'WORKPLACE_POST_CAN_NOT_COMMENT',
  WORKPLACE_CONFIG_NOT_FOUND = 'WORKPLACE_CONFIG_NOT_FOUND',

  /**
   * * Formulas
   */
  FORMULAS_INVALID = 'FORMULAS_INVALID',

  CANNOT_RESEND_OTP = 'CANNOT_RESEND_OTP',
  OTP_NOT_FOUND = 'OTP_NOT_FOUND',
  OPT_EXPIRED = 'OPT_EXPIRED',
  OTP_VERIFY_TOKEN_EXPIRED = 'OTP_VERIFY_TOKEN_EXPIRED',
  CANNOT_SEND_OTP = 'CANNOT_SEND_OTP',
  OTP_VERIFY_TOKEN_IS_REQUIRED = 'OTP_VERIFY_TOKEN_IS_REQUIRED',
  INVALID_OTP = 'INVALID_OTP',
  CAN_ONLY_REGISTER_ACCOUNT_BY_EMAIL_OR_PHONE_NUMBER = 'CAN_ONLY_REGISTER_ACCOUNT_BY_EMAIL_OR_PHONE_NUMBER',

  /**
   * * Webhook
   */
  WEBHOOK_IS_EXIST = 'WEBHOOK_IS_EXIST',
  WEBHOOK_NOT_FOUND = 'WEBHOOK_NOT_FOUND',

  /**
   * * Special Speak checkin
   */
  SPEAK_CHECKIN_NOT_FOUND = 'SPEAK_CHECKIN_NOT_FOUND',
  SPEAK_CHECKIN_EXISTED = 'SPEAK_CHECKIN_EXISTED',
  SPEAK_CHECKIN_SCOPES_INVALID = 'SPEAK_CHECKIN_SCOPES_INVALID',

  /**
   * * Advance Payment Configs
   */
  ADVANCE_PAYMENT_CONFIG_SCOPES_INVALID = 'ADVANCE_PAYMENT_CONFIG_SCOPES_INVALID',
  ADVANCE_PAYMENT_CONFIG_NOT_FOUND = 'ADVANCE_PAYMENT_CONFIG_NOT_FOUND',
  ADVANCE_PAYMENT_CONFIG_CODE_EXISTED = 'ADVANCE_PAYMENT_CONFIG_CODE_EXISTED',
  ADVANCE_PAYMENT_CONFIG_SCOPE_TYPE_ALL_EXISTED = 'ADVANCE_PAYMENT_CONFIG_SCOPE_TYPE_ALL_EXISTED',
  ADVANCE_PAYMENT_CONFIG_TYPE_PERCENT_CAN_NOT_EMPTY = 'ADVANCE_PAYMENT_CONFIG_TYPE_PERCENT_CAN_NOT_EMPTY',
  RANGE_ADVANCE_PAYMENT_CONFIG_CAN_NOT_EMPTY = 'RANGE_ADVANCE_PAYMENT_CONFIG_CAN_NOT_EMPTY',
  RANGE_ADVANCE_PAYMENT_CONFIG_NOT_VALID = 'RANGE_ADVANCE_PAYMENT_CONFIG_NOT_VALID',
  RANGE_ADVANCE_PAYMENT_CONFIG_DUPLICATED = 'RANGE_ADVANCE_PAYMENT_CONFIG_DUPLICATED',

  /**
   * User Link Account
   */
  USER_LINK_ACCOUNT_EXISTED = 'USER_LINK_ACCOUNT_EXISTED',
  USER_LINK_ACCOUNT_NOT_FOUND = 'USER_LINK_ACCOUNT_NOT_FOUND',
  CANNOT_UNLINK_ACCOUNT = 'CANNOT_UNLINK_ACCOUNT',
  INVALID_SEARCH_LINK_ACCOUNT = 'INVALID_SEARCH_LINK_ACCOUNT',
  PASSWORD_IS_REQUIRED = 'PASSWORD_IS_REQUIRED',
  ADVANCE_APPLIANCE_NOT_FOUND = 'ADVANCE_APPLIANCE_NOT_FOUND',
  CANNOT_REMOVE_ADVANCE_APPLIANCE = 'CANNOT_REMOVE_ADVANCE_APPLIANCE',
  ADVANCE_APPLIANCE_SUBMISSION_TIME_NOT_VALID = 'ADVANCE_APPLIANCE_SUBMISSION_TIME_NOT_VALID',
  REACH_LIMIT_SUBMISSION_ADVANCE_APPLIANCE = 'REACH_LIMIT_SUBMISSION_ADVANCE_APPLIANCE',
  CAN_ONLY_CHOOSE_TRANSFER_TYPE_SALARY_ACCOUNT = 'CAN_ONLY_CHOOSE_TRANSFER_TYPE_SALARY_ACCOUNT',
  REACH_LIMIT_MAXIMUM_ADVANCE_PAYMENT = 'REACH_LIMIT_MAXIMUM_ADVANCE_PAYMENT',
  CANNOT_ADVANCE_PAYMENT = 'CANNOT_ADVANCE_PAYMENT',
  ONLY_CAN_REMOVE_ADVANCE_APPLIANCE_PENDING = 'ONLY_CAN_REMOVE_ADVANCE_APPLIANCE_PENDING',
  CANNOT_CHANGE_ADVANCE_PAYMENT_CONFIG_TYPE = 'CANNOT_CHANGE_ADVANCE_PAYMENT_CONFIG_TYPE',
  CANNOT_CHANGE_ADVANCE_STATUS_TO_PENDING = 'CANNOT_CHANGE_ADVANCE_STATUS_TO_PENDING',
  CHANGE_ADVANCE_STATUS_NEED_FOLLOW_RULE = 'CHANGE_ADVANCE_STATUS_NEED_FOLLOW_RULE',
  ONLY_RECOVERIED_ADVANCE_STATUS_CAN_ADD_RECOVERY_ADVANCE = 'ONLY_RECOVERIED_ADVANCE_STATUS_CAN_ADD_RECOVERY_ADVANCE',
  NEED_TO_ADD_RECOVERY_ADVANCE = 'NEED_TO_ADD_RECOVERY_ADVANCE',
  RECOVERY_AMOUNT_MUST_LESS_EQUAL_THAN_ADVANCE_AMOUNT = 'RECOVERY_AMOUNT_MUST_LESS_EQUAL_THAN_ADVANCE_AMOUNT',
  ONLY_CAN_CHANGE_STATUS_MULTIPLE_ADVANCE_APPLIANCE_TO_ADVANCED = 'ONLY_CAN_CHANGE_STATUS_MULTIPLE_ADVANCE_APPLIANCE_TO_ADVANCED',
  INVALID_LINK_ACCOUNT_UPDATE_DATA = 'INVALID_LINK_ACCOUNT_UPDATE_DATA',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_EMAIL = 'INVALID_EMAIL',
  CANNOT_CHANGE_ADVANCE_APPLIANCE_STATUS = 'CANNOT_CHANGE_ADVANCE_APPLIANCE_STATUS',
  CANNOT_ADVANCE_PAYMENT_BY_SALARY_ACCOUNT = 'CANNOT_ADVANCE_PAYMENT_BY_SALARY_ACCOUNT',
  CANNOT_LINK_ACCOUNT = 'CANNOT_LINK_ACCOUNT',

  CAN_NOT_REMOVE_SYSTEM_CATEGORY_HAS_RELATION_DATA = 'CAN_NOT_REMOVE_SYSTEM_CATEGORY_HAS_RELATION_DATA',
  CAN_NOT_INACTIVE_SYSTEM_CATEGORY_HAS_RELATION_DATA = 'CAN_NOT_INACTIVE_SYSTEM_CATEGORY_HAS_RELATION_DATA',
  NOT_CHANGE_SHIFT_WHEN_END_SHIFT_HOUR = 'NOT_CHANGE_SHIFT_WHEN_END_SHIFT_HOUR',

  COMPANY_CODE_EXISTED = 'COMPANY_CODE_EXISTED',
  COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
  CAN_NOT_REMOVE_COMPANY_HAS_LABOR_CONTRACT = 'CAN_NOT_REMOVE_COMPANY_HAS_LABOR_CONTRACT',
  CHECK_PASSWORD_IS_REQUIRED = 'CHECK_PASSWORD_IS_REQUIRED',
  USER_ACCOUNT_HAS_NO_PASSWORD = 'USER_ACCOUNT_HAS_NO_PASSWORD',
  CAN_NOT_REMOVE_ALLOWANCE_HAVE_STAFF_APPLY = 'CAN_NOT_REMOVE_ALLOWANCE_HAVE_STAFF_APPLY',
  CAN_NOT_REMOVE_ACCOUNT_BECAUSE_HAVE_WORKPSPACE_NOT_SUPER_ADMIN = 'CAN_NOT_REMOVE_ACCOUNT_BECAUSE_HAVE_WORKPSPACE_NOT_SUPER_ADMIN',
  CAN_NOT_SETUP_REMOVE_ACCOUNT = 'CAN_NOT_SETUP_REMOVE_ACCOUNT',
  CAN_NOT_REMOVE_ACCOUNT_BECAUSE_OWNER_WORKSPACE = 'CAN_NOT_REMOVE_ACCOUNT_BECAUSE_OWNER_WORKSPACE',
  CHECKIN_CONFIG_NIGHT_SHIFT_HOUR_INVALID = 'CHECKIN_CONFIG_NIGHT_SHIFT_HOUR_INVALID',
  ERROR_CHECKIN_QR_CODE_LOCATION = 'ERROR_CHECKIN_QR_CODE_LOCATION',
  ERROR_CHECKIN_QR_CODE_NOT_FOUND_LOCATION = 'ERROR_CHECKIN_QR_CODE_NOT_FOUND_LOCATION',
  ERROR_CHECKIN_QR_CODE_NOT_BELONG_CONTACT = 'ERROR_CHECKIN_QR_CODE_NOT_BELONG_CONTACT',
  ERROR_CHECKIN_QR_CODE_TIMEOUT = 'ERROR_CHECKIN_QR_CODE_TIMEOUT',
  ERROR_CHECKIN_QR_CODE_REFRESH_QR = 'ERROR_CHECKIN_QR_CODE_REFRESH_QR',
  ERROR_CHECKIN_QR_CODE_NOT_BELONG = 'ERROR_CHECKIN_QR_CODE_NOT_BELONG',
  ERROR_CHECKIN_QR_CODE_NOT_QR_CODE = 'ERROR_CHECKIN_QR_CODE_NOT_QR_CODE',

  OVERTIME_INFO_NOT_FOUND = 'OVERTIME_INFO_NOT_FOUND',
  DATE_NOT_IN_CURRENT_MONTH = 'DATE_NOT_IN_CURRENT_MONTH',
  DATE_NOT_HAVE_OVERTIME = 'DATE_NOT_HAVE_OVERTIME',
  DATE_NOT_IN_RANGE = 'DATE_NOT_IN_RANGE',
  // workspace config

  WORKSPACE_CONFIG_NOT_FOUND = 'WORKSPACE_CONFIG_NOT_FOUND',

  // user workspace device

  USER_WORKSPACE_DEVICE_NOT_FOUND = 'USER_WORKSPACE_DEVICE_NOT_FOUND',
  LIMIT_ACCOUNT_LOGIN = 'LIMIT_ACCOUNT_LOGIN',
  LIMIT_DEVICE_LOGIN = 'LIMIT_DEVICE_LOGIN',
  ACCOUNT_CENSORED = 'ACCOUNT_CENSORED',
  DEVICE_CENSORED = 'DEVICE_CENSORED',
  INVALID_LIST_UPDATE = 'INVALID_LIST_UPDATE',
  INVALID_STATUS = 'INVALID_STATUS',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',

  // statistic human report

  HUMAN_REPORT_NOT_FOUND = 'HUMAN_REPORT_NOT_FOUND',
  HUMAN_REPORT_EXPORT_LIMIT = 'HUMAN_REPORT_EXPORT_LIMIT',
}

export default ERROR;
